aws-samples/generative-ai-use-cases

- README.md
- package-lock.json
- packages/cdk/lambda/createChat.ts
- packages/cdk/lambda/predict.ts
- packages/cdk/lambda/repository.ts
- packages/cdk/lambda/secret.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/database.ts
- packages/cdk/lib/construct/index.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/package.json
- packages/types/package.json
- packages/types/src/base.d.ts
- packages/types/src/chat.d.ts
- packages/types/src/index.d.ts
- packages/types/src/message.d.ts
- packages/types/src/protocol.d.ts
- packages/web/src/@types/predict.d.ts
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/usePredictor.ts
- packages/web/src/hooks/useTextToJson.ts
- packages/web/src/pages/NotFound.tsx
- ddb に登録するようにした
- 検索系や feedback 系はこの PR では対応していない
- マネコンで必要な query ができることは確認
- chat の init 時に chatId を作成してしまうと、画面を開くたびに空の chat ができてしまうため、最初のメッセージを送ったときに作成するようにした
- chat を作成しつつ、systemContext を最初のメッセージとして record する
- predict 関数は unrecorded (ddb に記録されていない) と recorded (ddb に記録されている) のメッセージを渡して、unrecorded のものを ddb に登録しつつ、推論結果を recorded にして返すという挙動にした
- skipRecording: true を渡せば ddb に記録されない (情報抽出のユースケースで利用)
- transaction だと時間 (createdDate) のずれがなく会話の復元に失敗する可能性があると思い、putItem はメッセージごとに行なっている
- web <=> lambda 間で protocol が必要だったため、workspace に共通で使う type definition を定義した types を追加した
> 会話履歴の登録部分の追加

- package-lock.json
- packages/cdk/lambda/createMessages.ts
- packages/cdk/lambda/predict.ts
- packages/cdk/lambda/repository.ts
- packages/cdk/lib/construct/api.ts
- packages/types/src/message.d.ts
- packages/types/src/protocol.d.ts
- packages/web/package.json
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useHttp.ts
- packages/web/src/hooks/usePredictor.ts
- packages/web/src/hooks/useTextToJson.ts
ポイントは以下です
- messageId をフロントエンドで付与することで、ddb に登録後に message の replace が安全にできるようになった (messageId を照合する)
- predict は llm の答えを text/plain で返すだけで、chat の作成と messages の記録は別 API とした
- streaming response を見据えた対応
> write 系のバックエンドの実装し直し

- packages/cdk/lambda/repository.ts
- packages/cdk/lambda/updateFeedback.ts
- packages/cdk/lib/construct/api.ts
- packages/types/src/protocol.d.ts
- packages/web/src/components/ButtonFeedback.tsx
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useChatApi.ts
- packages/web/src/pages/PromptTamplatePageBase.tsx
Feedback 送信機能を、とりあえずチャット画面 (履歴も含め) のみ対応しました。その他のユースケース別の実装の方にも追加可能ですが、多少リファクタリングを入れたいと思っているので (可能であれば ChatPage.tsx と統合したい) 別 Issue に上げさせてもらいます。Internal Knowledge Sharing ではチャットのみで十分だと思うので、取り急ぎ。
> Feedback 送信 (チャットのみ)

- README.md
- package.json
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/auth.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- setup-env.sh
> ローカルで検証する時に自動で環境変数が入るように

- packages/web/src/App.tsx
- packages/web/src/components/Drawer.tsx
- packages/web/src/pages/EditorialPage.tsx
- packages/web/src/pages/KendraSearchPage.tsx
- これまでツールという区分だったものをユースケースに変更
- Kendra を新しいツールという区分に追加
> Kendra を左カラムに追加

- packages/web/src/hooks/useChat.ts
fix: delete old chat
#63 
履歴からチャットを再開するとき、既に同じ chatId を持つ state があれば削除する仕様に
> fix: delete old chat

- packages/cdk/lambda/predictTitle.ts
#122
インプットとなるプロンプトから指示が混在していたため、タイトル生成のプロンプトを改善&アウトプットに含まれるXMLタグを除去
> XMLタグがタイトルに含まれる問題を修正

- packages/cdk/lib/generative-ai-use-cases-stack.ts
Changed
```
const ragEnabled: boolean = this.node.tryGetContext('ragEnabled') || false;
const selfSignUpEnabled: boolean =
this.node.tryGetContext('selfSignUpEnabled') || true;
```
to 
```
const ragEnabled: boolean = this.node.tryGetContext('ragEnabled')!;
const selfSignUpEnabled: boolean =
this.node.tryGetContext('selfSignUpEnabled')!;
```
> Fixed bug in disable self-signup feature

- packages/web/src/components/Drawer.tsx
- packages/web/src/components/ExpandableField.tsx
- packages/web/src/components/ExpandableMenu.tsx
- packages/web/src/pages/EditorialPage.tsx
- packages/web/src/pages/SummarizePage.tsx
- packages/web/src/pages/TranslatePage.tsx
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/188
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/183
リンクだけデフォルトで閉じているようにしました
ExpandedField を継承しようと思いましたが、label や RowItem などの仕様と合わせるのが厳しく別にコンポーネントを作成しました
ExpandedField を ExpandableMenu に合わせて rename しました
<summary>
左カラムのメニューを展開可能な形式に変更しました。
Drawer、ExpandableField、各ページコンポーネントを修正して展開動作を実装。
新規にExpandableMenuコンポーネントを作成し、展開メニューの再利用性を高めました。
</summary>
> 左カラムのメニューを expandable に

- packages/web/src/components/ChatList.tsx
- packages/web/src/components/ChatListItem.tsx
- packages/web/src/components/Drawer.tsx
- packages/web/src/components/TextEditor.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/194
<summary>
<changeSet>
---
packages/web/src/components/ChatList.tsx
packages/web/src/components/ChatListItem.tsx  
packages/web/src/components/Drawer.tsx:
会話履歴一覧にキーワード検索機能を追加しました。stateフックとuseMemoフックで入力キーワードに基づき会話履歴をフィルタリングしています。また、検索語にマッチする部分をハイライト表示するコンポーネントを導入しました。インターフェイスや動作への影響はありません。
---
packages/web/src/components/TextEditor.tsx:  
会話履歴内のコメントにキーワード検索機能を追加しました。要約文にクラス名を付与して検索語にマッチする部分をハイライト表示できるようにしました。これによりユーザーはコメントを簡単に検索できるようになります。インターフェイスや動作への影響はありません。
</changeSet> 
</summary>
> 会話履歴の簡易検索機能

- packages/web/src/components/ExpandableField.tsx
- packages/web/src/pages/WebContent.tsx
抽出前テキストがラベルと見間違えるとフィードバックを受け、下部に持って行きました。
> Web コンテンツ抽出画面微修正

- README.md
- docs/DEPLOY_OPTION.md
- packages/cdk/cdk.json
- packages/cdk/lambda/checkEmailDomain.ts
- packages/cdk/lib/construct/auth.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
ユーザの登録時にメールアドレスを制限できる機能を作成しました。こうしたプルリクを送るようなことが不慣れなため、おかしな点があれば、遠慮なくお伝えください
目的
- 社内のユーザのみが使用できる設定を追加したい
- 管理者がCognitoでユーザを作成しなくて済む方法が良い
- 社内のユーザであれば、誰でも自由に登録できるようにしたい
実装内容
- 特定のメールアドレスのドメインを持ったユーザのみサインアップできるようにするために、以下をCDK（バックエンド）に追加した
- 許可するドメインをStringのリストで設定するデプロイ時のオプションを追加した
- ドメイン判定用のLambda関数を作成した
- メールアドレスと許可ドメインを受け取り、メールアドレスの@以降がいずれかに該当するかチェックする
- Cognitoのサインアップ前 Lambdaトリガーとして、上記のLambda関数を設定する処理を追加した
動作確認
- npm run cdk:deployで、自分のAWSアカウントにデプロイできることを確認した
- Lambda関数が作成された（GenerativeAiUseCasesStack-AuthCheckEmailDomainxxxx）
- Cognitoのユーザプールのサインアップ前 Lambda トリガーとして、Lambda関数が登録された
- 以下のように、allowedSingUpEmailDomainsを変えながらデプロイし、該当するドメインのメールアドレスで登録が可能か不可能かをチェックし、想定通りであることを確認した（ユーザの削除は毎回Cognitoのユーザーのリストから手動で行いました）
- …
> add functions to check emal domain of signup user

- packages/web/src/prompts/index.ts
- 画像生成プロンプトの修正：`<step>` や `<output-format>` などのタグに入れて出力することが確率であるため、`<output></output>`タグで囲むよう指示を追加。
> 画像生成プロンプトの修正

- packages/cdk/lambda/predictStream.ts
> predictStream でLLMの出力が終わったあとに lambda がすぐに停止するように変更

- packages/web/src/components/PromptList.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/242
> プロンプト集のつまみの上下のクリック判定をなくす

- packages/cdk/lambda/utils/models.ts
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/components/Tooltip.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/RagPage.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/252
bedrock の icon の下に Help.tsx を配置して hover すると表示されるようにした。
> modelId を表示

- package.json
ローカル開発環境の構築用のカスタムスクリプトが、一部の環境で動作しない問題の修正です。
具体的な原因までは特定できていないですが、以下の環境では動作しませんでした
- OS : Amazon Linux 2023
- Shell : fish
「source ./setup-env.sh」と変更することで動作しました。
> ローカル開発環境構築用のカスタムスクリプトが、一部の環境で動作しない問題の修正

- packages/web/src/index.css
以下の Pull Request では、一律で width を 50vw としていた。
https://github.com/aws-samples/generative-ai-use-cases-jp/commit/a5546aae28c02a420a6f1411b208621f84673b83
小さい画面だと、code 要素の横幅が小さく違和感があった
一律で 50vw ではなく、小さい画面の場合は width 80vw にする変更。
> 小さい画面での横スクロール幅を変更

- packages/cdk/lib/construct/database.ts
デプロイ時に table が再生成されることはない (アップデートされる) ことは確認済みです。
> DynamoDB を provisioned から on demand に変更

- packages/web/src/components/Markdown.tsx
- packages/web/src/hooks/useRagFile.ts
- packages/web/src/pages/KendraSearchPage.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/297
また、表題の通り Kendra 検索で S3 のドキュメントリンクがクリックできなかったので、これも併せて修正しました
> RAGチャットのS3のファイルをダウンロードする際にローディング表示する、Kendra 検索でもドキュメントを開けるようにする

- README.md
- docs/DEPLOY_OPTION.md
- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/cdk.json
- packages/cdk/lib/search-agent-stack.ts
#226 
- Knowledge base for Amazon Bedrock デプロイ方法のドキュメント更新
- `agentEnabled` はエージェントの利用、`searchAgentEnabled` は検索エージェント用のスタックのデプロイに役割を変更
- 検索エージェント用のスタックの名前を変更
> Knowledge base for Amazon Bedrock 向けにデプロイ手順を変更

- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/lib/construct/auth.ts
- packages/cdk/lib/construct/web.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/web/src/App.tsx
- packages/web/src/components/AuthWithSAML.tsx
- packages/web/src/components/AuthWithUserpool.tsx
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/hooks/useRag.ts
- packages/web/src/main.tsx
- packages/web/src/pages/AgentChatPage.tsx
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/EditorialPage.tsx
- packages/web/src/pages/GenerateTextPage.tsx
- packages/web/src/pages/KendraSearchPage.tsx
- packages/web/src/pages/RagPage.tsx
- packages/web/src/pages/Setting.tsx
- packages/web/src/pages/SharedChatPage.tsx
- packages/web/src/pages/SummarizePage.tsx
- packages/web/src/pages/TranscribePage.tsx
- packages/web/src/pages/TranslatePage.tsx
- packages/web/src/pages/WebContent.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/293
ファイルの変更数が多いですが、lint 漏れがあったみたいで、実際に変更したのは packages/web/src/hooks/useRag.ts のみです！
> RAGの検索結果が空の場合に、生成動作を切り替える

- README.md
- docs/DEPLOY_OPTION.md
- package-lock.json
- package.json
- packages/cdk/.gitignore
- packages/cdk/cdk.json
- packages/cdk/ecs/recognize-file/Dockerfile
- packages/cdk/ecs/recognize-file/app/main.py
- packages/cdk/ecs/recognize-file/requirements.txt
- packages/cdk/lambda/getMediaUploadSignedUrl.ts
- packages/cdk/lib/construct/file.ts
- packages/cdk/lib/construct/index.ts
- packages/cdk/lib/construct/recognize-file.ts
- packages/cdk/lib/construct/transcribe.ts
- packages/cdk/lib/construct/web.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/package.json
- packages/types/src/protocol.d.ts
- packages/web/src/App.tsx
- packages/web/src/hooks/useFile.ts
- packages/web/src/hooks/useFileApi.ts
- packages/web/src/main.tsx
- packages/web/src/pages/FileUploadPage.tsx
- packages/web/src/pages/Setting.tsx
- packages/web/src/vite-env.d.ts
- setup-env.sh
#147 
- Python の unstructured ライブラリを使用したファイルの読み込み機能の追加
- Lambda では動かすことができないと判断したため（unstructured が /tmp 以外の領域への書き込みを行う点、コールドスタートが 10s を超えてしまう点など）、ECS Fargate 上で動かしている
- API Gateway -> NLB -> ECS Fargate の構成を取り、他の API と共通の URL、認証を使用する
> ファイルアップロード機能

- packages/cdk/lib/construct/auth.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/301
自分の IP で正常に設定 & 動作していることを確認しています。
> IdentityPool の IAM ロールの Condition に SourceIP を追加

- packages/cdk/lambda/predict.ts
- packages/cdk/lambda/predictStream.ts
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lambda/utils/models.ts
- packages/types/src/protocol.d.ts
- packages/types/src/utils.d.ts
- packages/web/src/components/GenerateImageAssistant.tsx
- packages/web/src/hooks/useChat.ts
#270 
stop_sequences に </output> を入れることで、json を出力し終わった後に、テキストを出力させないようにする。
テキスト出力で JSON から出力させる仕組みはまた別途。
> 画像生成 use case の prompt 生成に stop_sequences を追加する

- packages/cdk/lambda/predict.ts
- packages/cdk/lambda/predictStream.ts
- packages/cdk/lambda/predictTitle.ts
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lambda/utils/prompter.ts
- packages/types/src/protocol.d.ts
- packages/web/src/components/GenerateImageAssistant.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/pages/AgentChatPage.tsx
- packages/web/src/pages/GenerateTextPage.tsx
- packages/web/src/pages/LandingPage.tsx
- packages/web/src/pages/SummarizePage.tsx
- packages/web/src/pages/TranslatePage.tsx
- packages/web/src/pages/WebContent.tsx
- `<output>` タグを promptTemplate に埋め込むことで、Claude の Assistant の出力は必ず `<output> ~ </output>` で囲まれるようになった
- これにより、extraSuffix、stopSequences の実装が不要になった (マルチモデル対応する上で <output> のハードコーディングを削除したかった)
- promptTemplate に `<output></output>` を埋め込んでいるので、フロントエンドで `<output></output>` を排除する処理を消すことができた (これもマルチモデル化において必須)
- Assistant の出力が `<output>~</output>` 前提なので、Claude 用のプロンプトでは原則「出力は `<output></output>` で囲んでください」の一言が必要になる。(すでに現状そうなっている) ただ、実際はその指定がなくても `Assistant: <output>` から始まるので、Claude が察して `<output></output>` で出力してくれる。
- `<output> {` で 100% json のみを出力させる、という Tips が使えなくなる。しかし、現状の画像生成ユースケースでも `<output>` しか指定していないので、問題ないと判断。
- 全てのデモが問題なく実施できることを確認 (ただし、チャットだけ出力が変わっているので、プロンプトを変更)
- 現状、タイトル予測のプロンプトが Claude 決め打ちになっているが、これは後ほど対応する。
> [DNM] <output> タグを promptTemplate に埋め込む

- packages/cdk/lambda/predictTitle.ts
- packages/types/src/protocol.d.ts
- packages/web/src/hooks/useChat.ts
- packages/web/src/prompts/claude.ts
- packages/web/src/prompts/index.ts
- これまで Lambda にハードコーディングされていて、Claude 以外のモデルに対応する際に問題になることは明白
- Prompt の生成は Frontend に統一
> タイトル生成用のプロンプトはモデルごとに定義するように変更

- packages/types/src/message.d.ts
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/components/InputChatContent.tsx
- packages/web/src/components/ZoomUpImage.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useFiles.ts
> 画像にローディング表示を追加

- packages/web/src/prompts/claude.ts
これまでのプロンプトが
```
<conversation>
...会話の json
</conversation>
<conversation></conversation>XMLタグの内容から30文字以内でタイトルを作成してください。...
```
となっていたので、会話の json が無視され、二個目の <conversation></conversation> がからの会話履歴と判定されていた模様です。そこでいくつか修正を加え、1 つめの <conversation></conversation> が会話履歴ということを理解してもらうようにしました。
> 「空のXMLタグ」といったタイトルが生成される件の修正

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
> Claude3 Haikuに対応

- packages/cdk/lib/construct/api.ts
- packages/web/src/hooks/useTyping.ts
- Claude 3 Haiku の出力が早く、現状の TYPING_DELAY=10 だけでは逆に UX を損ねている
- 現状は固定で 1 文字ずつタイピングアニメーションしているが、入力が必要な文字列の増加に応じて入力文字列単位も増加させる
- なお、TYPING_DELAY を 10 から減らしても UX は改善しなかった (おそらくすでに delay ではなく処理そのものに律速している)
> タイピングスピードを残りの文字列数に応じて変化させる

- .github/workflows/deny-cdk-context-json.yml
- docs/DEPLOY_OPTION.md
- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/cdk.json
- packages/cdk/lib/construct/recognize-file.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
cdk.jsonでVPC IDを指定した場合、既存のVPCにECSクラスタとNLBをデプロイします。これはVPCの数やElastic IPの数などのクォータによってデプロイできないケースを回避し、NAT Gatewayのコストを節約します。
既存のVPCは `Vpc.fromLookup` で参照します。これを使用するためには、デプロイ先のAWSアカウントとリージョンが指定されている必要があるため、スタックの`env`プロパティを指定しました。また、cdk.context.jsonが生成されます。このファイルはユーザーが使用する場合はGitにコミットすべきですが、このリポジトリは公開されたサンプルであるため、コントリビューターのcdk.context.jsonが誤ってコミットされるべきではありません。セキュリティリスクと意図しない挙動を回避するために、cdk.context.jsonが含まれるPRを拒否するためのGitHub Actionsを含めました。
既存のVPCを `Vpc.fromVpcAttributes` で参照することも検討しましたが、指定しなければならない項目が多く、誤った指定をした場合の挙動がデバッグしづらいため、採用しませんでした。
---
> feat: ファイルアップロード機能で既存のVPCにデプロイできるようにする

- packages/cdk/bin/generative-ai-use-cases.ts
- packages/web/src/@types/navigate.d.ts
- packages/web/src/App.tsx
- packages/web/src/hooks/useFiles.ts
- packages/web/src/hooks/useTyping.ts
- packages/web/src/main.tsx
- packages/web/src/pages/VideoAnalyzerPage.tsx
- packages/web/src/prompts/claude.ts
- packages/web/src/prompts/index.ts
- 映像分析のユースケースを追加
- 分析テキスト送信時にウェブカメラのフレーム画像をマルチモーダルモデルに送信
- useChat と連携しているため、分析したフレームは後から会話履歴から見れる
- 同じ命令を複数回送信する可能性を考慮し、送信後に入力をリセットしていない
README.md 等のドキュメント対応はこちらの PR が merge されたら別で対応します！
> [新規ユースケース] 映像分析

- packages/web/src/prompts/claude.ts
#409 
追加のコンテキストを入れても変な文言が出ないように修正
> 校生機能のプロンプト修正

- docs/DEPLOY_OPTION.md
なし
モデルの選択に関する Document を、理解しやすい更新です。
- 東京リージョンで Claude 2.1 のモデルを追加
　Claude Instant しか例に記載がなかったため、2.1 を追加
- バージニアリージョンで、Claude 3 Haiku の指定を例に追加
　意図 : Haiku の生成スピードやコスト感を他のモデルと比較しやすいように、例に Haiku を追加
> モデルの選択に関するドキュメントについて、Claude 2.1 や Claude 3 Haiku の説明を追加

- packages/web/src/pages/GenerateImagePage.tsx
- packages/web/src/pages/WebContent.tsx
気になったところを微修正しました
- Web コンテンツ抽出で元文章を fetch している時に loading を表示するように変更
- Prompt がない時に画像生成の「生成」ボタンがクリックできないように変更
> UI を微修正 (Web コンテンツ抽出・画像生成)

- README.md
- docs/DEPLOY_OPTION.md
- packages/cdk/cdk.json
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lib/construct/api.ts
Bedrock サービスのみ、別の AWS アカウントを指定して構成する
- Bedrock 用 AWS アカウント で IAM Role を手動で作成しておく
- 作成した IAM Role を cdk.json に手動で書く
- packages/cdk/cdk.json
- roleArn と sessionName を追加した。
- roleArn に "arn:aws:iam::アカウントID:role/ロール名" を指定することにより、別の AWS アカウント上の Bedrock サービスを利用できるようになる。
- sessionName にはデフォルト値を設定済みである。
- packages/cdk/lib/construct/api.ts
- 上記を Lambda 環境変数に設定する
- roleArn が指定されている場合に AssumeRole 用のポリシーを設定
- packages/cdk/lambda/utils/bedrockApi.ts
- roleArn が設定されている場合に AssumeRole する
- cdk デプロイできることを確認した
- ユースケース一覧が動作することを確認した
- roleArn 設定時に Bedrock アカウントのみ、トークン数などが増えていることを CloudWatch Metrics から確認した
- roleArn 非設定時に アプリケーションデプロイ用アカウントのみ、トークン数などが増えていることを CloudWatch Metrics から確認した
> 別アカウントの Bedrock を利用するためのクロスアカウント設定を追加

- packages/web/src/pages/EditorialPage.tsx
- packages/web/src/pages/TranslatePage.tsx
毎度自動が ON になるのが嫌だったので実装しました。
Auto_xxx の書式は https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/web/src/components/ExpandableMenu.tsx#L16 ここを継承しました。
> 自動翻訳・自動校正の state を local storage に保存するように

- packages/web/src/pages/EditorialPage.tsx
- packages/web/src/pages/TranslatePage.tsx
他にもレイアウト崩れあると思いますが、機能にアクセスできないのは致命的だと思うので一旦こちらのみ修正しました。
> スマホで見た時に自動xxボタンが見えるように修正

- packages/web/src/components/Markdown.tsx
> 校正と文書生成で出力が左に偏ってしまうのを修正

- packages/cdk/lib/construct/web.ts
NodejsBuild の処理の中で、JavaScript heap out of memory error が発生していました。
割り当てているコンピューティング環境は現在 "3 GB メモリ、2 vCPU" です。（deploy-time-build の NodejsBuild Construct の Default）
<details>
<summary>CodeBuild Error log</summary>
```
[Container] 2024/06/04 00:46:34.288780 Running on CodeBuild On-demand
--
2 | [Container] 2024/06/04 00:46:34.288793 Waiting for agent ping
3 | [Container] 2024/06/04 00:46:34.490210 Waiting for DOWNLOAD_SOURCE
4 | [Container] 2024/06/04 00:46:35.006026 Phase is DOWNLOAD_SOURCE
5 | [Container] 2024/06/04 00:46:35.006928 CODEBUILD_SRC_DIR=/codebuild/output/src856953380/src
6 | [Container] 2024/06/04 00:46:35.006985 YAML location is /codebuild/readonly/buildspec.yml
7 | [Container] 2024/06/04 00:46:35.007228 No commands found for phase name: install
8 | …
```
> fix: JavaScript heap out of memory error on CodeBuild

- packages/cdk/lambda/utils/models.ts
- packages/types/src/image.d.ts
- packages/web/src/components/Button.tsx
- packages/web/src/components/ExpandableField.tsx
- packages/web/src/components/SketchPad.tsx
- packages/web/src/pages/GenerateImagePage.tsx
- #162, #404
- #507 
- #332 
- 類似画像生成をワンクリックでできるボタンの追加
- Titan Image の similarityStrength パラメータの対応
- 解像度が 512 x 512 固定だったのを変更できるように対応
- リファクタリング
別 PR で Inpaint / Outpaint を実装するため事前のコード整理も行っています。
> 画像生成ユーズケースの改善（解像度, 類似画像生成改善)

- docs/DEPLOY_ON_AWS.md
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/522
> jq インストール手順の追加

- packages/cdk/lambda/repository.ts
- packages/cdk/lambda/updateSystemContextTitle.ts
- packages/cdk/lib/construct/api.ts
- packages/types/src/protocol.d.ts
- packages/web/src/components/PromptList.tsx
- packages/web/src/hooks/useSystemContextApi.ts
- packages/web/src/pages/ChatPage.tsx
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/432
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/489
- #489 で出た UI 実装案とは若干異なるもの (常時編集ボタンが表示されているか、編集ボタンの表示非表示を切り替えられるかの違いという認識) ですが、常時表示でも (個人的に) 邪魔にならず、かつ `「保存したシステムコンテキスト」を選択したときに、「プロンプト例」を選択したときと同様にチャット画面に遷移したい` の要件は満たすためそのように実装しています。
> 保存したシステムコンテキストのタイトル変更

- packages/cdk/lambda/summit/ehon/create_image.py
- packages/cdk/lambda/summit/ehon/create_scene.py
- packages/cdk/lambda/summit/ehon/create_summary.py
- packages/cdk/lib/construct/summit/ehon.ts
[Summit 2024向け特別展示] 
絵本生成機能について、Bedrock API は us-east-1 リージョンを指定するように変更
> [Summit 2024向け特別展示] Bedrock API は us-east-1 リージョンを指定

- packages/cdk/lambda/utils/bedrockAgentApi.ts
- packages/web/src/components/Markdown.tsx
- packages/web/src/pages/AgentChatPage.tsx
#524 
- Agent のレスポンスに Attribution が含まれる際、レスポンスを含めるように変更。
- 微修正：複数の参考文献を表示する際 `sup` タグの隙間がないため UI を微修正。
- 微修正：Agent のセッション情報がリセット時に新規セッションに変更されない問題を修正。
> Agent のレスポンスに Attribution を追加

- packages/web/src/hooks/useRag.ts
RAGチャットを利用したとき、リンク先のURLに以下が含まれていると、リンクが崩れる
- 半角スペース
- #411 でも言及されている内容
- 半角カッコ "(" ")"
変更点
- item.DocumentURIにencodeURIを適用し、半角カッコをエスケープするようにした
動作確認
- S3に半角スペース・半角カッコが含まれるファイルをアップロードした
- RAGチャットを使用してリンクをクリックしたとき、ファイルが表示された
> RAGチャットのリンクを修正

- docs/DEPLOY_OPTION.md
- packages/cdk/cdk.json
- packages/cdk/lib/rag-knowledge-base-stack.ts
#548 
Knowledge Bases を有効化すると、OpenSearch Serverless が自動的に作成される。
その際に、2 OCU が利用されるが、PoC などの場面でコストを削減するために、redundancy を無効化することで 1 OCU に削減ができ、料金が約半額になる。そのための機能を追加する。
デフォルトのパラメーターは 「冗長化なし (false)」としている。理由としては、以下の 2 点
- GenU を初めて使い始めるお客様を想定し、PoC で検証を始められる場合のコストを最小化
- Kendra を利用した RAG の場合は、デフォルトでは Developer Edition で作成され、シングル AZ で構成される。これと似た意味を持つように OpenSearch Serverless でも利用する。
> RAG で Knowledge Bases を利用するときに、コストを削減するために OpenSearch Serverless の冗長性を無効化できる機能を追加

- packages/cdk/lib/rag-knowledge-base-stack.ts
- OSS Collection にアップデートが入ったさいに description がないと表題のエラーになる。
- Description があるとエラーが出なかったので、追加した。
- 詳細は https://github.com/aws-samples/generative-ai-use-cases-jp/issues/559
> OpenSearch Serverless の Description がないと特定の条件下で Description cannot be empty エラーがでる

- packages/web/src/hooks/useRag.ts
現状のKendra RAGでは、Retrieve時に過去クエリの履歴を考慮しておらず、複数回クエリを行う場合に文脈が考慮されないケースがあったため、クエリ生成時に過去のユーザー入力を考慮したクエリを生成するように変更。
> Kendra RAG / ユーザーコンテキストを考慮したクエリ生成

- packages/cdk/lib/rag-knowledge-base-stack.ts
None
AWS マネジメントコンソール上の挙動の修正です。
Data source の Source Link をクリックしても、S3 のページが開かれません。
理由としては、末尾のスラッシュが無いことにより、マネジメントコンソール上でうまく扱うことができないエラーです。
・Before
docs
・after
docs/
> マネジメントコンソールの Knowledge bases のページで、S3 へのリンクが正常に動作していない問題の修正

- packages/web/src/pages/ChatPage.tsx
Chatページにおける、以下の問題を解決しました
- jpgファイルをアップロード対象として選択できない
- ドラッグアンドドロップでチャットに追加できない
（jpegファイルは利用できるのにも関わらず）
以下の点を変更しました
- ChatPageのFileLimitのacceptに、jpgを追加した
*動作確認* 
以下のように動作確認しました
- Chatページで、jpgファイルをアップロード対象として選択できた
- ドラッグアンドドロップでチャットに追加できた
- その後、会話を続け、画像に関する会話ができた
> add jpg as accept file for ChatPage

- packages/cdk/lambda/utils/models.ts
max_tokensの設定がモデル上限より小さいものについて、上限値に変更。
※Claude 3.5 Sonnetはヘッダを変更することで8192トークンまで出力できる(beta)が、現時点では対応せず4096トークンとなっている。
> adjust max_tokens for each model

- packages/cdk/lib/construct/agent.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/transcribe.ts
enforceSSLがtrueとなっていないS3バケットが4つほどあったため、いずれもenforceSSLをtrueを付与しました。
（trueとなっていない場合、Control Towerが有効な環境においてエラーとなるケースがあるようです）
動作確認
* 変更後、デプロイできること
* デプロイ後、音声認識やチャット（画像添付あり）のユースケースが動作すること
> enforceSSLが未適用のS3バケットについて、enforceSSLを有効化

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
Remove llama2 from supported models due to deprecation of the legacy models after 12-Aug, 2024
> Remove llama2

- browser-extension/src/@types/backend-api.d.ts
- browser-extension/src/app/features/chat/ChatMessage.tsx
- browser-extension/src/app/features/chat/chatSlice.ts
- browser-extension/src/app/features/chat/useChat.ts
- browser-extension/src/app/features/highlight-menu/HighlightMenu.tsx
- browser-extension/src/pages/chat/ChatPage.tsx
「続きを出力」でResponse形式が変わったので、その修正です。
（「続きを出力」には対応していません）
> [拡張機能] Response形式変更に伴う修正

- packages/cdk/lambda/agent.ts
- packages/cdk/lambda/repository.ts
- packages/cdk/lambda/utils/bedrockAgentApi.ts
- packages/types/src/agent.d.ts
- packages/types/src/index.d.ts
- packages/types/src/message.d.ts
- packages/types/src/protocol.d.ts
- packages/web/src/components/ChatMessage.tsx
- packages/web/src/hooks/useChat.ts
#607 
- Agent のトレースをトグル内（details, summary）に表示
- DynamoDB データ型の変更: trace を追加
- カスタムアクション（検索アクション含む）、Knowledge Base、Code Interpreter に対応
- 微修正：Code Interpreter にて同一ファイルが複数回出現するため初出のみ表示するように修正
> Agent のトレースを表示

- packages/cdk/lambda/getTranscription.ts
- packages/cdk/lambda/startTranscription.ts
- packages/types/src/protocol.d.ts
- packages/web/src/hooks/useMicrophone.ts
- packages/web/src/hooks/useTranscribe.ts
- packages/web/src/pages/TranscribePage.tsx
- packages/web/src/pages/TranslatePage.tsx
#201 #419 #538
- Transcribe の複数話者の話者特定に対応
- 話者登録: 複数話者の際、名前をカンマ区切りで入れることで話者 ID  spk_{i} を置き換え可能
- テストケース: ファイル/リアルタイム、日本語/英語、複数話者 ON/OFF の8ケースで検証。
- 微修正: Translate の音声入力で onClick と useEffect で二重に startTranscription が実行され出力が二重になる問題の修正
> Transcribe の複数話者対応

- README.md
- docs/DEPLOY_OPTION.md
- packages/web/src/components/DialogConfirmDeleteChat.tsx
- packages/web/src/hooks/useRagKnowledgeBase.ts
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/LandingPage.tsx
"Knowledge Base"および"Agents"の表記を統一しました。
AWS公式ドキュメントの表記では「Knowledge bases for Amazon Bedrock」を採用していますが、AWS公式のサービス紹介やAWS Summitの発表資料では「Knowledge Bases」という表記を採用しているため、こちらに統一しました。
併せて、ソースコード内のキャンセルボタンは日本語の表記で統一しました。
> ソースコードおよびドキュメントの表記ゆれを修正

- packages/web/src/hooks/useRag.ts
- packages/web/src/utils/URLUtils.ts
#610 #411  #355
- Kendra のリンクが正しく表示されるように修正
- Kendra の DocumentURI の仕様: S3 パスは日本語空白括弧含め正しくエンコードされている一方ウェブサイトのURLなどはエンコードされておらず日本語は動作するが空白や `)` により URL 自体は問題ないものの Markdown のリンクが壊れる。
- 現在の実装の課題: Web に合わせた実装になっているためすでにエンコードされている S3 DocumentURI が二重にエンコードされている。
- 修正点:
- エンコードされてない場合のみエンコード（日本語と空白と多重エンコードに対応）
- [RFC3986 に則ったエンコード](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#encoding_for_rfc3986) （括弧など encodeURI がエンコードしない特殊記号をエンコードし Markdown リンクの崩壊を防ぐ）
- 検証:
- S3: 日本語、半角スペース、半角括弧等が含まれたファイルを S3 にアップロード し S3 データソースにて検証。 
- Web Crawler: 日本語、半角スペース、半角括弧等が含まれた[ウェブサイト](https://maekawataiki.github.io/PageTest/index.html)を用意し Web Crawler v3 データソースにて検証。
By submitting this pull request, I confirm …
> Kendra RAG の リンクの修正

- packages/web/src/hooks/useRagKnowledgeBase.ts
本プルリクエストでは、RAG チャット (Knowledge Base) 機能に以下の2点の変更を行いました。
1. **Knowledge Bases for Amazon Bedrock の追加データソースへの対応**
2. **後処理の脚注付与方法の改良**
**変更の概要**
- **目的**: Knowledge Bases for Amazon Bedrock が Web クローラー等の新たなデータソースに対応したため、S3 以外のデータソースをデプロイ済みの Knowledge Base に追加した際に RAG チャットで利用できるようにするための変更です
- **変更点**:
- `convertS3UriToUrl` 関数を修正し、変換に失敗した場合は元の URI をそのまま返すよう変更しました。
変更によって、S3 以外のデータソース利用時に脚注の URI が空になる問題に対応しました。
- `retrievedItemsKendraFormat` の生成方法を変更し、`location?.s3Location?.uri` の代わりに各種データソースで共通して URI を取得できる `metadata?.['x-amz-bedrock-kb-source-uri']` を使用するよう変更しました。
`location` キーを用いる場合はデータソースごとに異なる名称が返却されるため、参照先を変更しています。変更にあたって、 [Retrieve - Amazon Bedrock](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html)  を参照しました。
- **目的**: …
> Knowledge Bases for Amazon Bedrockのデータソース対応と脚注付与方法の改善

- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/lib/construct/guardrail.ts
- packages/cdk/lib/guardrail-stack.ts
*Issue #:* #641
AWS::Bedrock::GuardrailVersionリソースは、Guardrailの現在の設定のスナップショットを保持するイミュータブルなリソースです。このため、Guardrailの設定を更新しても、作成済みのGuardrailVersionには反映されません。
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrock-guardrailversion.html
GuardrailVersionを使用せず、APIでは `DRAFT` バージョンを指定してGuardrailを適用します。これにより、Guardrailの設定変更は即座にAPIに反映されるようになります。
すでにGuardrailを有効にしてデプロイしたユーザーは、この修正を反映したあとにクロススタック参照のデプロイエラーを経験します。解決策は、GuardrailStackを更新する前にGenerativeAiUseCasesStackを単独で更新することです。
```sh
npx cdk deploy GenerativeAiUseCasesStack --exclusively
npx cdk deploy --all
```
詳細については #641 を参照してください。
> feat: GuardrailVersionリソースを削除してDRAFTバージョンを使用する

- packages/cdk/lib/construct/api.ts
N/A
大きめのDocumentをインプットにした際に、Lambda(PredictStream)がメモリ不足で終了し、推論が中断される動作を確認したため、対策としてメモリを256MBに増量する。
> change memorySize of predictStreamFunction from 128MB(default) to 256MB

- docs/DEPLOY_OPTION.md
- packages/cdk/lib/construct/common-web-acl.ts
WAFに IP アドレス制限と国コード制限の両方を設定した場合に、「許可されたIPアドレスかつ、許可された国」のアクセスだけ許可するように変更しました。
※現状は、OR条件で判定している。
> WAFのルール設定を変更

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/684
https://aws.amazon.com/jp/blogs/aws/upgraded-claude-3-5-sonnet-from-anthropic-available-now-computer-use-public-beta-and-claude-3-5-haiku-coming-soon-in-amazon-bedrock/
> Upgraded Claude 3.5 Sonnet  V2 in Amazon Bedrock

- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/681
> サーバーアクセスのログ記録の設定元と設定先のS3バケットが同一になっている

- docs/DEPLOY_OPTION.md
- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- Custom::CDKBucketDeployment がタイムアウトするのは RAG の docs 用の bucket に大量のアクセスログが存在しているから
- 大量のアクセスログが存在してしまっている件は https://github.com/aws-samples/generative-ai-use-cases-jp/pull/689 で修正済み (アクセスログは別の bucket に吐くように修正された)
- ただし、既存ユーザーは RAG の docs 用 bucket に大量のアクセスログがまだ存在するため、デプロイ時にそれらのファイルを削除しようとしてタイムアウトすることがある
- https://github.com/aws-samples/generative-ai-use-cases-jp/pull/672 の対応で exclude: ['AccessLogs/*'] オプションを追加したが、この対応は不完全で、ログの出力先を AccessLogs に変更した対応の前から存在する logs* ファイルが排除されていなかった。
(これが今回の対応) exclude の対象に logs* を追加することで、全てのログファイルを対象外に
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/681
- https://github.com/aws-samples/generative-ai-use-cases-jp/pull/693 (間違った対応。マージされていない。)
> デプロイ時に Custom::CDKBucketDeployment がタイムアウトするバグの修正

- packages/cdk/lambda/queryKendra.ts
- packages/cdk/lambda/retrieveKendra.ts
Kendra の Query/Retrieve における AttributeFilter を削除し、下記のエラーを解消。
> (ValidationException) "AttributeFilter cannot have 0 operators. It must have one and only one."
N/A
> fix kendra's query/retrieval parameters

- packages/web/src/hooks/useRag.ts
- packages/web/src/hooks/useRagKnowledgeBase.ts
- Knowledge Base のレスポンスにページ番号が含まれる場合、footnote に追加する処理を実装
- 参考: https://docs.aws.amazon.com/bedrock/latest/userguide/kb-test-config.html
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/543
> Add page number for knowledge base response

- packages/web/src/components/ChatMessage.tsx
- packages/web/src/components/ModalSystemContext.tsx
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/SharedChatPage.tsx
GenU にはチャットユースケースにてシステムコンテキストを保存する機能があるが、会話履歴ページとシェアページでも保存できるようにした。
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/439
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/438
> システムコンテキストを会話履歴とシェアページから保存可能に

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
- packages/types/src/text.d.ts
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/599
> Llama2 の削除

- packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
ユースケース新規作成/編集画面のヘルプに表示される、サンプルの可変項目のスペースを削除しました。
スペースなしが適切かと思っております。
ご確認のほどよろしくお願いいたします。
- [ x] npm run lint を実行した
- [ x] 手元の環境で動作確認済み
N/A
> ユースケースビルダーヘルプのサンプル可変項目のスペースを削除

- packages/web/src/hooks/useChat.ts
- (主に続きを出力時に) Assistant の最後のメッセージが空白で終わっている時にそのまま推論するとエラーになる
- trimEnd() して、trim した分の空白をあとから付与する処理をしていた
- trimEnd() したらその分の空白は次の推論で付与されるはずなので、不要な処理だった。
N/A
> 不要なトリム処理の削除

- packages/cdk/lambda/useCaseBuilder/useCaseBuilderRepository.ts
- packages/types/src/useCaseBuilder.d.ts
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/hooks/useCaseBuilder/useMyUseCases.ts
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderExecutePage.tsx
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderMyUseCasePage.tsx
ユースケースビルダーの利用者目線では、モデルの選択が必要ないケースが多い。
むしろ隠すことで、利用する際の心理的障壁を取り除く意図がある。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/751
> [ユースケースビルダー] モデルの固定化

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
Novaのクロスリージョン推論用のモデルIDを追加しました
"us.amazon.nova-pro-v1:0",
"us.amazon.nova-lite-v1:0",
"us.amazon.nova-micro-v1:0",
- [x ] npm run lint を実行した
- [x ] 関連するドキュメントを修正した
- [x ] 手元の環境で動作確認済み
> Add Nova Cross Region Model IDs

- packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/utils/UseCaseBuilderUtils.ts
`retrieve*` だけでは入力フォームはできず、`{{text}}` とセットで使うパターン
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/733
> [ユースケースビルダー] Amazon Kendra と Knowledge Base の Retrieve に対応 (埋め込みのみバージョン)

- packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
- packages/web/src/utils/UseCaseBuilderUtils.ts
- packages/web/tests/use-case-builder/items.test.ts
Amazon Kendra と Knowledge Base の Retrieve 結果を取得する inputType を作成しました。
これにより、基本的な RAG を含め、社内のデータを活かしたさまざまなユースケースが作成できます。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/733
> [ユースケースビルダー] Amazon Kendra と Knowledge Base の Retrieve に対応

- packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
`{{retrieveKendra}}` `{{retrieveKnowledgeBase}}` をサイレントリリースしたことに伴い、説明を体系化した。
Help を右から遷移させるような表示方法ではなく、プレビュー画面が置き換わるような実装に変更した。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/733
> [ユースケースビルダー] Help の改善

- packages/cdk/lambda/useCaseBuilder/useCaseBuilderRepository.ts
- packages/types/src/useCaseBuilder.d.ts
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/hooks/useCaseBuilder/useMyUseCases.ts
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
- packages/web/src/pages/useCaseBuilder/UseCaseBuilderExecutePage.tsx
ユースケースビルダーでファイル添付の ON/OFF を切り替えられるようにしました。
placeholder に `{{file}}` 的なものがあるかで判定すると言った案もありましたが、Converse API の仕様上 `{{file}}` の位置に意味がないことと、既存の useFiles を reuse する上で最もシンプルな方法としてこの実装にしています。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/731
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/730
> [ユースケースビルダー] マルチモーダル対応 (ファイル添付対応)

- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/common/src/model.ts
- packages/types/src/message.d.ts
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useFileApi.ts
- packages/web/src/pages/ChatPage.tsx
- 課題
- Lambda 経由で動画をアップロードした際 Lambda のリクエスト上限 1 MB 以上のデータを送信した際エラーとなる。
- https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
- 変更
- 動画は S3 経由で Bedrock に渡す形式に変更。
- ただし現状 S3 経由での受け渡しは us-east-1 のみのサポートのため、クロスリージョンでない Amazon Nova のみ Video Chat を有効化するフラグに変更
- chore
- クロススタック参照されているパラメータを明示的にエクスポートする。（Nested Stack 削除時にエラーになるため）
> Video Chat の修正

- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
label の width が full だったので cursor-pointer じゃない領域でもファイル添付が起動していました。
w-fit に修正しました。
N/A
> ファイル添付ボタンのクリック領域を調整

- packages/cdk/lambda/utils/models.ts
- packages/types/src/image.d.ts
- packages/web/src/components/Select.tsx
- packages/web/src/pages/GenerateImagePage.tsx
画像生成 Titan v2 と Amazon Nova Canvas の新しい 3 つの機能に対応。
画像コンディショニング、カラーパレットによる画像ガイダンス、背景の削除。
https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-titan-image.html
https://docs.aws.amazon.com/nova/latest/userguide/image-gen-access.html
[756](https://github.com/aws-samples/generative-ai-use-cases-jp/issues/756)
複雑な conflict 対応のため、過去の [PR](https://github.com/aws-samples/generative-ai-use-cases-jp/pull/603) を使用して新規ブランチで実装しております。
> 画像生成 Titan v2 & Nova Canvas 新機能対応

- README.md
- docs/DEPLOY_OPTION.md
- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/cdk.json
- packages/cdk/lib/construct/agent.ts
- packages/cdk/lib/construct/common-web-acl.ts
- packages/cdk/lib/construct/guardrail.ts
- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- setup-env.sh
- 複数スタックでデプロイした際に競合しうる、リソースを修正。
- 新たに `env` を context に追加。デフォルトは空文字で既存ユーザーは引き続き同様に利用できるが、env を設定すると別スタックとしてまとめてデプロイすることが可能。
- Agent / Guardrail / WAF の物理名にユニークな Suffix を付与。物理名の変更のためリソースは再作成されるがドリフトがない限りは既存ユーザーへの影響はない。
- Kendra および Knowledge Base はデータへの影響がある可能性があるためユニークな Suffix ではなく `env` を Suffix として利用。（デフォルトは空文字なので既存環境への影響はない）
#500 
#646 
#787
> 複数スタックデプロイ時のリソース名の修正

- packages/cdk/lambda/predictTitle.ts
- packages/cdk/lambda/utils/models.ts
- packages/common/src/model.ts
- packages/types/src/model.d.ts
- タイトル生成時に使用するモデルをアプリで有効化されているモデルで軽量なモデルを優先
- 有効化されている軽量モデルのうち最初のものを優先して利用。
- 軽量なモデルが有効化されていない場合は有効化されているモデルの最初のモデルに Fall back。
#719
#789
> タイトル生成モデルを軽量モデルに

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/common/src/model.ts
- packages/web/src/pages/GenerateImagePage.tsx
- us-west-2 のみ対応しております。以下のように cdk.json を変更して確認お願いします。
```
"modelRegion": "us-west-2",
"imageGenerationModelIds": [
"stability.sd3-5-large-v1:0",
]
```
- 別タスクですが、GenerationMode の説明 Tooltip も追加しております。
#793
> 画像生成 Stable Diffusion 3.5 Large への対応

- packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
- 以前の挙動では更新時に「更新」メニューにとどまるため、更新完了時に急に「更新内容がありません」と表示されて意味が分かりにくかった
- 更新完了時にアプリ定義メニューに遷移するように変更した
- ミニマムでどこの作業が必要なのかわかりにくいので、対応が必要なメニューにドットを表示するようにした
- エラーがない場合 (作成・更新が可能な場合) は作成・更新メニューにドットを表示するようにした。
なし
> [ユースケースビルダー] 対応が必要なメニューにドットを表示

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/models.ts
- packages/common/src/application/model.ts
- packages/web/src/pages/GenerateImagePage.tsx
- 画像ソリューション対応に Canvas, SD 系モデルが漏れていたため追加
- 新バージョン (stability.stable-image-ultra-v1:1, stability.stable-image-core-v1:1) 追加
- こちらの[リンク](https://docs.aws.amazon.com/ja_jp/bedrock/latest/userguide/models-supported.html)の順番に並べてます。PR の際にご活用ください。
> 画像生成ドキュメント修正 & Stablity AI モデル新バージョン追加

- README.md
- packages/web/src/hooks/useDiagram.ts
- packages/web/src/prompts/claude.ts
- packages/web/src/prompts/index.ts
- Readmeでダイアグラム生成動画のパスを修正し忘れていて動画が映っていなかったのでパスの修正。
- typoの修正
- useDiagram.tsの不必要なimportの削除
修正し忘れていたところがあったので変更です。再度レビューお願いします!
> 【ダイアグラム生成】Readmeの修正とその他の細かな修正

- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
ユースケースビルダーの出力が途中で止まった際、続きを出力できるようにした。
動作確認は https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/cdk/lambda/utils/models.ts#L89 を 100 などに絞って行ってください。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/807
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/785
> [ユースケースビルダー] 続きを出力ボタンの設置

- packages/web/src/components/ChatMessage.tsx
今までの 改行 + break-all 方式から whitespace-pre-wrap に変更。
正常にコードがインデントされている様子
長い文章では折り返される
なし
> ユーザーの入力もインデント等が正常に描写されるように修正

- README.md
- docs/DEPLOY_OPTION.md
- docs/DEVELOPMENT.md
- packages/cdk/cdk.json
- packages/cdk/lib/construct/web.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/lib/stack-input.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
- packages/types/src/index.d.ts
- packages/types/src/useCases.d.ts
- packages/web/src/App.tsx
- packages/web/src/hooks/useUseCases.ts
- packages/web/src/main.tsx
- packages/web/src/pages/LandingPage.tsx
- packages/web/src/vite-env.d.ts
- setup-env.sh
`hiddenUseCases` を指定することで基本ユースケースの表示/非表示が切り替えられるようにしました。現状、デフォルトでは全てのユースケースが表示されます。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/679
> 特定のユースケースを非表示にすることを可能にするオプション

- packages/web/src/components/ScrollTopBottom.tsx
- packages/web/src/pages/ChatPage.tsx
チャット履歴を印刷する際、不要なコンポーネント(モデル選択プルダウン、システムコンテキストトグルスイッチ、シェアボタン、スクロールボタン)が描画されないよう調整
> チャット履歴の印刷時のビューを最適化

- packages/cdk/lib/construct/rag.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
* Kendra の sync を実行すると発生するエラーを解消しました
* https://github.com/aws-samples/generative-ai-use-cases-jp/pull/802 でコミットされた `packages/cdk/rag-docs/docs/bedrock-ug.pdf.metadata.json` が Kendra ではで sync エラーの原因になっている
* エラーメッセージは `Found invalid Metadata file s3:....`
* Kendra 用の S3 バケットには、当該ファイルをアップロードしないための変更を実施しています
- [*] `npm run lint` を実行した
- [*] ~~関連するドキュメントを修正した~~ 修正箇所無し
- [*] 手元の環境で動作確認済み
- [*] `npm run cdk:test` を実行しスナップショット差分がある場合は `npm run cdk:test:update-snapshot` を実行してスナップショットを更新した
なし
> Kendra の sync エラー解消

- package-lock.json
- packages/web/package.json
- packages/web/src/components/DiagramRenderer.tsx
- packages/web/src/components/EditableMarkdown.tsx
- packages/web/src/pages/GenerateDiagramPage.tsx
ダイアグラム生成において、Bedrock の生成による Markdown syntax error や、編集を可能とする。
[Markdown Editor](https://github.com/uiwjs/react-md-editor) を使用するために、package.json に追加してます。
https://github.com/user-attachments/assets/95ce1561-ecb5-42d4-8378-a1c54988acff
> ダイアグラム生成のマークダウンを編集可能にする

- packages/cdk/lib/construct/agent.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
Search agentでユーザー入力を有効化するアクショングループの定義を修正しました。
内容：`actionGroupName`を`UserInput`から`UserInputAction`に変更
理由：`actionGroupName`が`UserInputAction`でないとAgentのユーザ入力が有効化されないため (Case sensitive)
なし
> Search agentでユーザー入力を有効化するアクショングループの定義を修正

- packages/types/src/message.d.ts
- packages/web/src/components/InputChatContent.tsx
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/hooks/useFiles.ts
- packages/web/src/pages/VideoAnalyzerPage.tsx
- setup-env.sh
すでにファイルがアップロードされている状態で別のファイルをアップロードし、ロード中にアップロード済みのファイルを削除するとロード中のファイルが認識されなくなるバグを修正しました。
s3アップロード前後でファイルオブジェクト配列のインデックスが変化することに起因するため、UploadedFileTypeに別途idを用意しインデックスの再検索を行うよう変更しました。
> ファイルアップロード中にアップロード済みのファイルの削除した際のバグの解消

- docs/DEPLOY_OPTION.md
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/web/src/hooks/useFiles.ts
- これまでは agentEnabled が true でないと Agent チャットユースケースが利用できなかった
- 手動追加した Agent のみを利用したい場合、これだと不便
- agentEnabled は Agent スタックを作成するかのフラグに仕様変更し、手動追加された Agent がある場合は agentEnabled が false でも Agent チャットユースケースが利用できるようにした。
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/887
> agentEnabled が false でも agents に Agent が定義されていたら Agent チャットユースケースを有効にできるように変更

- docs/mkdocs/material/overrides/home.html
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lambda/utils/models.ts
- packages/common/src/application/model.ts
- packages/types/src/message.d.ts
- packages/types/src/model.d.ts
- packages/types/src/text.d.ts
- packages/web/src/components/InputChatContent.tsx
- packages/web/src/components/ModelParameters.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/pages/ChatPage.tsx
- Claude 3.7 Sonnet の Reasoning に対応
- chore: Claude 3.5 以降の max token を 8192 に増加
> Reasoning support for claude 3.7 sonnet

- .github/workflows/close-stale-issues.yml
- 30日間動きがないと警告コメントとラベルが付与される
- そこから14日間動きがないと削除される
- [-] `npm run lint` を実行した
- [-] 関連するドキュメントを修正した
- [-] 手元の環境で動作確認済み
- [-] `npm run cdk:test` を実行しスナップショット差分がある場合は `npm run cdk:test:update-snapshot` を実行してスナップショットを更新した
N/A
> 動きがない Issue/PR の自動削除 workflow

- packages/web/src/components/Select.tsx
- packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
- packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
- packages/web/src/utils/UseCaseBuilderUtils.ts
- packages/web/tests/use-case-builder/items.test.ts
- セレクトボックスを定義する `{{select}}` を追加
- 選択肢は `{{select:ラベル:選択肢1,選択肢2}}` のように定義する。(そのためラベルは省略不可。)
- 仕様の詳細は「ヘルプ」と単体テストを確認していただけると
- https://github.com/aws-samples/generative-ai-use-cases-jp/issues/732
> [ユースケースビルダー] `{{select}}` の追加

- docs/DEPLOY_OPTION.md
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lambda/utils/models.ts
- packages/cdk/lib/agent-stack.ts
- packages/cdk/lib/cloud-front-waf-stack.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/web.ts
- packages/cdk/lib/create-stacks.ts
- packages/cdk/lib/dashboard-stack.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- packages/cdk/lib/stack-input.ts
- packages/cdk/parameter.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
- packages/cdk/test/generative-ai-use-cases.test.ts
- packages/types/src/message.d.ts
- packages/types/src/model.d.ts
- packages/types/src/utils.d.ts
- packages/web/src/hooks/useModel.ts
- packages/web/src/pages/RagKnowledgeBasePage.tsx
テキスト生成と画像生成について、複数リージョンを同時に利用できるようにした。
現状できないこと：modelRegion以外のAgent/Knowledge Base/Flowsを指定する
残作業
- メトリクスはマルチリージョン対応確認。しかし、Prompt LogsはmodelRegionに指定したリージョンでの推論しか表示できない
現状の制限事項
- 異なるリージョンで同じ名前のモデルを指定すると意図した動作とならない
#932
> 複数リージョンのモデルを同時に指定する

- .github/workflows/close-stale-issues.yml
- Stale Issue の operations-per-run を 100 に変更。
> incrase GitHub Action operations per run

- packages/cdk/lambda/repositoryVideoJob.ts
- packages/cdk/lambda/utils/bedrockApi.ts
- packages/cdk/lambda/utils/models.ts
- packages/types/package.json
- packages/types/src/message.d.ts
- packages/types/src/video.d.ts
- packages/web/src/components/Base64Image.tsx
- packages/web/src/hooks/useFiles.ts
- packages/web/src/hooks/useVideo.ts
- packages/web/src/pages/GenerateImagePage.tsx
- packages/web/src/pages/GenerateVideoPage.tsx
- Nova Reel の最初のフレーム画像を指定できるようにした
- Nova Canvas で 1280x720 サイズの画像を作成できるようにした
- FileLimit に strictImageDimensions を指定できるようにした (画像の幅と高さの指定)
> 動画生成 Nova Reel 最初のフレーム画像を指定できるように

- .github/release-drafter.yml
- .github/workflows/close-stale-issues.yml
- .github/workflows/publish-release.yml
- .github/workflows/release-drafter.yml
- .github/workflows/update-version.yml
- packages/web/src/hooks/useVersion.ts
- release drafter: Add changes pushed to main branch to draft release (create draft release if none exists)
- update version: Create PR to update version in package.json to match draft release tag
- publish release: Publish draft release when update version PR is merged
N/A
> Add workflow to automate versioning

- packages/web/index.html
- packages/web/tailwind.config.ts
以下のキャプチャーの様にフォントの読み込みに失敗しているので、修正のプルリクエストです。
スペースを含むフォントの場合は、ダブルクオーテーションで囲う必要があるようです。
修正後以下の様にフォントが読み込まれています。
M PLUS Rounded 1c だと、以下のような形で、サイズによってはあまりきれいではないので、 Noto Sans JP に変えてプルリクエストさせていただいています。
M PLUS Rounded 1c
Noto Sans JP
フォント自体の変更を行うかどうかはご判断いただき、変えない方がいい場合は、 M PLUS Rounded 1c にダブルクオーテーションを付けた形でマージしていただければと思います。
> fix font family and change noto sans jp

- packages/web/src/components/InputChatContent.tsx
- チャット入力空欄の時は Validation で送信できないが、空白（半角、全角）の時は Validation が通るが Bedrock 側でエラーになる問題の修正。
> チャット入力が空白の場合の修正

- packages/web/src/hooks/useFiles.ts
- Safari でファイルアップロードが失敗する問題の修正
- Safari だと `ReadableStreamBYOBReader` をサポートしていないため ArrayBuffer にフォールバック
> Fix for file upload failure issue in Safari

- packages/cdk/lib/agent-stack.ts
- packages/cdk/lib/cloud-front-waf-stack.ts
- packages/cdk/lib/construct/agent.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/auth.ts
- packages/cdk/lib/construct/common-web-acl.ts
- packages/cdk/lib/construct/rag-knowledge-base.ts
- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/construct/transcribe.ts
- packages/cdk/lib/construct/use-case-builder.ts
- packages/cdk/lib/construct/web.ts
- packages/cdk/lib/dashboard-stack.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
This PR implements a safety improvement by making all props properties readonly in CDK constructs and stacks to prevent unintended property overrides.
`N/A`
> fix: prevent unintended override of construct and stack props

- packages/cdk/lib/construct/api.ts
Added default authorization settings to all API Gateway methods using `defaultMethodOptions` to fix CWE-285 security vulnerability.
`N/A`
> fix: CWE-285 in API Gateway

- .github/pull_request_template.md
- .husky/pre-commit
- docs/en/DEVELOPMENT.md
- docs/ja/DEVELOPMENT.md
- package-lock.json
- package.json
In this PR, by introducing `husky`, developers can notice that they forgot to run `npm run lint` at the time of commit.
`N/A`
> feat(git hooks): introduce husky

- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
RAG document uploads sometimes fail.
According to error logs, there's insufficient memory.
Addressed by increasing memory to 1024 MB.
N/A
> Fix: Received response status [FAILED] from custom resource. Message returned: Command ... died with <Signals.SIGKILL: 9>.

- packages/cdk/lib/construct/rag.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
We recently added nova-ug.pdf in rag-docs/docs/ as a sample document written in English.
If user uploaded their private docs manually into the bucket, the docs will be deleted since docs under the rag-docs was updated as above when user execute `npm run cdk:deploy`.
By adding `prune: false`, the docs manually uploaded will be remaining.
N/A
> Do not delete files in the RAG bucket

- packages/cdk/lib/create-stacks.ts
I just refactored the algorithm to remove duplicate regions in the video model.
`N/A`
> chore: refactor duplicate regions in video model

- packages/web/src/prompts/claude.ts
チャットで書いた内容によっては、左下の履歴に表示される要約タイトルに余計な英文が混ざることがあります。
これを避けるために、タイトル生成のプロンプトに少し修正を加えました。
この変更適用前と後のサンプルを以下に記載しています。
・適用前
・本修正適用後
プロンプト
```
patchコマンドの使い方を教えてください。
A.txt が元ファイル、 B.txtが修正後のファイルとして、そこからpatchファイルを作成する方法を教えててください。
```
マージ可能かどうかをご検討ください。
> fix title generation prompt

- docs/ja/DEPLOY_OPTION.md
- packages/web/src/prompts/claude.ts
Previously, search queries were always generated in English, which reduced search accuracy for non-English languages in Kendra. This PR fixed the query generation to use the same language as the user's question, improving non-English search accuracy.
> Fix query generation prompt

- packages/web/src/prompts/claude.ts
When Kendra RAG responses contained links, they were sometimes incorrectly rendered by the Markdown component. Instructions were added to the prompt to provide caution about links.
- https://github.com/aws-samples/generative-ai-use-cases/issues/1061
> Fix: Issue with links generated by Kendra RAG chat (Kendra RAGチャットで生成されたリンクの不具合)

- packages/cdk/lambda/utils/models.ts
- packages/cdk/lambda/utils/promptCache.ts
**Issues**
- Setting a cache point just after an image with Amazon Nova models causes an error
- Currently, setting cache points just after documents or videos isn't supported, making caching inefficient
**Changes**
- Modified the order in the message from `text -> files` to `files -> text (-> cache point)`
> fix: caching error of images with Amazon Nova

- packages/web/public/locales/translation/th.yaml
このPRの後に更新された translate のテキストにタイ語ファイルを追従させました。
（Voice  ChatとApp Title）
> fix thai text about voice chat and app title

- packages/cdk/lib/stack-input.ts
cdk.jsonやparameter.ts で hiddenUseCases に voiceChat = true を設定しても反映されなかったので修正しました。
> fix voice chat menu in hiddenUseCases

- packages/web/public/locales/translation/en.yaml
- packages/web/public/locales/translation/ja.yaml
- packages/web/src/components/PromptList.tsx
- packages/web/src/pages/ChatPage.tsx
It's hard to find the prompt list button at the right-top on the chat page.
I added the button to open the list at the center of the chat page. 
N/A
> Add "View Prompt Examples" button on landing page

- packages/common/src/application/model.ts
This PR implements prompt caching support for Claude Opus 4 and Claude Sonnet 4.
> Support prompt caching for Claude 4 models

- packages/cdk/lambda/utils/promptCache.ts
- packages/cdk/lib/construct/api.ts
- packages/common/src/application/model.ts
- packages/web/src/hooks/useModel.ts
Added functionality to append a CRI suffix to model display names when multiple instances of the same model are used. When a model is used only once, the display name remains unchanged.
#1082
> Add CRI suffix to model display name when duplicate models exist

- packages/web/public/locales/translation/en.yaml
- packages/web/public/locales/translation/ja.yaml
- packages/web/public/locales/translation/th.yaml
- packages/web/src/hooks/useTyping.ts
- packages/web/src/hooks/useUserSetting.ts
- packages/web/src/pages/Setting.tsx
I've made it possible for users to toggle the typing animation on and off. Also, since user-specific settings will increase in the future, I've separated the items into user settings and system settings.
https://github.com/aws-samples/generative-ai-use-cases/issues/1089
> Allow users to configure settings to turn off streaming

- packages/cdk/lib/construct/web.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
This fix allows Transcribe's Websocket connection in Content-Security-Policy.
※ I assume modifying `https://*.amazonaws.com` to `https://*.amazonaws.com:*` as a rational solution; however, I recommend implementing the minimal necessary changes to address the observed error.
https://github.com/aws-samples/generative-ai-use-cases/issues/1099
> Allow Transcribe Websocket connection in Content-Security-Policy

- packages/web/public/locales/translation/en.yaml
- packages/web/public/locales/translation/ja.yaml
- packages/web/src/components/Drawer.tsx
- packages/web/src/components/DrawerItem.tsx
Currently, the display/hide of use cases can be controlled at the system level, but it should also be possible to do so at the user level.
https://github.com/aws-samples/generative-ai-use-cases/issues/1090
> Allow user to configure the visibility of use cases.

- packages/cdk/lib/construct/web.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
Videos were not playing due to CloudFront's CSP configuration.
Fixed by adding media-src.
https://github.com/aws-samples/generative-ai-use-cases/issues/1110
> Bug fix for video playback issue

- packages/web/src/components/ButtonSend.tsx
- packages/web/src/components/GenerateImageAssistant.tsx
- packages/web/src/components/InputChatContent.tsx
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useRag.ts
- packages/web/src/pages/AgentChatPage.tsx
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/FlowChatPage.tsx
- packages/web/src/pages/RagKnowledgeBasePage.tsx
- packages/web/src/pages/RagPage.tsx
I have implemented a function to forcibly stop responses during Chat, RagChat, RagKnowledgeBaseChat, and AgentChat.
- ./src/pages/ChatPage.tsx => Made it possible to stop
- ./src/pages/RagPage.tsx => Made it possible to stop
- ./src/pages/RagKnowledgeBasePage.tsx => Made it possible to stop
- ./src/pages/AgentChatPage.tsx => Made it possible to stop
- ./src/pages/FlowChatPage.tsx => Loading & disabled as before
- ./src/pages/VoiceChatPage.tsx => Same as before (used in system prompt settings)
- ./src/pages/VideoAnalyzerPage.tsx => Loading & disabled as before
- ./src/components/GenerateImageAssistant.tsx => Loading & disabled as before
(ButtonSend component is only used in InputChatContent.tsx.)
N/A
> Implementation of forced stop function for chats

- packages/web/public/locales/translation/en.yaml
- packages/web/public/locales/translation/ja.yaml
- packages/web/src/components/Drawer.tsx
- packages/web/src/hooks/useLocalStorage.ts
- packages/web/src/hooks/useUserSetting.ts
- packages/web/src/pages/Setting.tsx
In this PR, user can configure the drawer. User can change the visibility of Use Case Builder and Tools even if system enables those mode and tools.
- https://github.com/aws-samples/generative-ai-use-cases/issues/1098
- https://github.com/aws-samples/generative-ai-use-cases/issues/1097
> User can configure the drawer (Setting the visibility of Use Case Builder and Tools)

- packages/web/src/hooks/useModel.ts
- packages/web/src/hooks/useOneshotTranslation.ts
- packages/web/src/pages/GenerateVideoPage.tsx
Prompts for Video generation are in English only. Currently, users need to translate prompts using the translation use case and then input them, which is cumbersome. We have now enabled translation capability within the Video generation use case. It performs one-shot inference using the same prompt as the /translate use case, but it doesn't remain in the conversation history.
https://github.com/aws-samples/generative-ai-use-cases/issues/1102
> Adding translation functionality for Video generation use case

- packages/cdk/lib/construct/web.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
When Custom domain is set, it causes a CSP error in CloudFront. I modified it to add the domain to CSP when samlCognitoDomainName is not null. In the case of Cognito domain, although it duplicates the setting with https://*.amazoncognito.com, I have confirmed that there is no operational issue.
- https://github.com/aws-samples/generative-ai-use-cases/issues/1116
> Bug where login fails with CSP error when custom domain is configured for Cognito

- packages/web/src/components/Textarea.tsx
This pull request addresses an issue with height calculation in Firefox.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1795904
- https://bugzilla.mozilla.org/show_bug.cgi?id=1787062
Changes:
- Added a Firefox-specific workaround to force layout recalculation before measuring scroll height
- Improved keyboard event handling by using React's built-in onKeyDown property
- Replaced useEffect with useLayoutEffect for better synchronization with the rendering cycle
> fix: Firefox textarea scrolling issues due to incorrect height calculation

- packages/cdk/lambda/utils/media.ts
- packages/cdk/lambda/utils/models.ts
- packages/common/src/application/media.ts
- packages/web/src/utils/MediaUtils.ts
In certain environments (e.g., Windows Chrome), `file.type` returns an empty string, causing invalid mimeType error.
This PR implements two fixes:
- Added custom extension-to-mimeType mapping instead of relying on `file.type`
- Implemented fallback for empty mimeType for backward compatibility
#1139
> fix: empty mimeType error on Windows

- packages/web/src/App.tsx
The status of Voice Chat and MCP Chat is "experimental" now. The architecture would be changed in the future.
Add experimental flag on UI so that user can identify the status of them.
https://github.com/aws-samples/generative-ai-use-cases/issues/1146
> Add "Experimental" flag properly

- packages/cdk/cdk.json
- packages/cdk/lib/stack-input.ts
cdk.json の初期のモデルを変更して、Claude Sonnet 4、Claude Opus 4 を追加しました。
Claude Sonnet 4 を一番上にしています。Claude 3.7 Sonnet や Claude 3.5 Haiku は引き続き利用することを考えて残しております。 
---
I have modified the initial model in cdk.json to add Claude Sonnet 4 and Claude Opus 4.
I've placed Claude Sonnet 4 at the top. I've kept Claude 3.7 Sonnet and Claude 3.5 Haiku as they will continue to be used.
> Add Claude 4 model to defaul models

- packages/cdk/mcp-api/Dockerfile
- packages/cdk/mcp-api/app.py
UV_PROJECT_ENVIRONMENT を設定したら動くようになったので設定
#1161
> Fix MCP Chat that stopped working

- packages/cdk/lib/construct/mcp-api.ts
- packages/cdk/mcp-api/app.py
- packages/web/src/prompts/claude.ts
Fixed the following
- Fixes an issue where Lambda fails to start due to lack of ephemeral storage
- Fixed an error when generating images from regions where Nova Canvas is not provided
- Fixed an issue where generated images sometimes did not appear on the chat screen
---
以下の点を修正
- Lambdaのエフェメラルストレージ不足で起動に失敗する問題の修正
- Nova Canvasが提供されていないリージョンから画像を生成するとエラーになる問題の修正
- 時々、生成した画像がチャット画面に表示されない問題の修正
> fix MCP chat

- docs/en/DEPLOY_OPTION.md
- docs/ja/DEPLOY_OPTION.md
- packages/cdk/cdk.json
- packages/cdk/lambda/agent.ts
- packages/cdk/lib/agent-stack.ts
- packages/cdk/lib/construct/agent.ts
- packages/cdk/lib/stack-input.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
- packages/cdk/test/generative-ai-use-cases.test.ts
- packages/types/src/agent.d.ts
Tavily Search API is available for search agents.
Tavily is available without a credit card for a free frame.
---
検索エージェントでTavily Search APIを利用できるようにしました。
Tavilyは無料枠であればクレジットカードなしで利用できます。
> Add tavily to search agent

- docs/en/DEPLOY_OPTION.md
- docs/ja/DEPLOY_OPTION.md
- packages/cdk/bin/generative-ai-use-cases.ts
- packages/cdk/cdk.json
- packages/cdk/consts.ts
- packages/cdk/custom-resources/apply-tags.js
- packages/cdk/custom-resources/package-lock.json
- packages/cdk/custom-resources/package.json
- packages/cdk/lib/create-stacks.ts
- packages/cdk/lib/rag-knowledge-base-stack.ts
- packages/cdk/lib/stack-input.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap.fix
When adding cost management tags to OpenSearch Serverless Collection, CloudFormation fails with the error:
```
CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename 3hf17j1yj99d59m78e0k and update the stack again.
```
This occurs because CloudFormation attempts to replace the existing resource when adding tags directly to the `CfnCollection` construct.
This PR implements a solution that adds tags to OpenSearch Serverless Collection using a separate Custom Resource instead of directly adding tags to the collection definition. This approach avoids the CloudFormation replacement error by:
1. Creating the collection without tags in the CloudFormation template
2. Using a dedicated Custom Resource to apply tags via AWS SDK after the collection is created …
> Fix OpenSearch Serverless Collection Tagging Without Replacement

- packages/cdk/lambda/utils/bedrockAgentApi.ts
- packages/web/src/hooks/useChat.ts
- packages/web/src/hooks/useChatApi.ts
- packages/web/src/hooks/useMeetingMinutes.ts
- packages/web/src/hooks/useWriter.ts
There is a bug where agent responses can be very large, and sometimes only part of the JSON is yielded, causing JSON.parse to fail. To address this, I implemented a process that temporarily saves the data (tmpBuffer) when JSON.parse fails, then combines it with the next chunk and attempts to parse again. Note that when characters become garbled after decoding with TextDecoder, they are converted to different "garbled characters," and even if you encode them again with TextEncoder, you end up with a different Uint8Array. Therefore, I added an option to predictStream to yield raw Uint8Array data. By default, it yields characters after decoding with TextDecoder, so this won't affect other existing implementations that use predictStream.
エージェントのレスポンスは非常に大きいことがあり、時々 JSON の一部のみが yield …
> [v5] Fix agent mojibake

- packages/common/src/application/model.ts
- packages/types/src/text.d.ts
- packages/web/public/locales/translation/en.yaml
- packages/web/public/locales/translation/ja.yaml
- packages/web/public/locales/translation/th.yaml
- packages/web/public/locales/translation/vi.yaml
- packages/web/public/locales/translation/zh.yaml
- packages/web/src/components/ButtonToggle.tsx
- packages/web/src/components/InputChatContent.tsx
- packages/web/src/components/ModelParameters.tsx
- packages/web/src/components/Tooltip.tsx
- packages/web/src/pages/AgentChatPage.tsx
- packages/web/src/pages/AgentCorePage.tsx
- packages/web/src/pages/ChatPage.tsx
- packages/web/src/pages/FlowChatPage.tsx
- packages/web/src/pages/McpChatPage.tsx
- packages/web/src/pages/RagKnowledgeBasePage.tsx
- packages/web/src/pages/RagPage.tsx
- packages/web/src/pages/VoiceChatPage.tsx
- Reasoning の切り替えを toggle で制御できるように (token budget は modal のまま)
- UI 上の reasoning を extended thinking に rename
- InputChatContent の textarea の領域を変更
- 以前は flex-col で textarea と buttons を縦に分割していたが、これによりスクロールバーの位置がおかしかった。これを flex-row に変更した。)
- この影響で InputChatContent は最低でも 2 行表示 (textarea 1 行と buttons で計 2 行になった)
- その影響で、InputChatContent をページ下部に配置しているページの padding bottom を 36 から 48 に変更
- InputChatContent の buttons に tooltip を表示するように
- 小さい tooltip を表示するオプションを Tooltip.tsx に新設
- Deepseek-R1 の reasoning 機能の有効化
- Chat.tsx の overrideModelParameters や AdditionalModelRequestFields の reasoningConfig は undefined を受け付けないように変更
- reasoning が無効なモデルに overrideModelParameters を送っても問題ないことが確認できたため、コード可読性の観点から undefined を削除
- むしろ、reasoning が enabled で budgetTokens が undefined の際にエラーになるため、それも型定義上発生しないように修整された …
> Reasoning toggle

- packages/cdk/lambda/utils/auth.ts
- packages/cdk/lib/construct/api.ts
- packages/cdk/lib/construct/closedNetwork/cognito-private-proxy.ts
- packages/cdk/lib/generative-ai-use-cases-stack.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
In closed network mode, a cognito proxy is used, so changes to jwksUri are necessary. (Since there is no VPC Endpoint, the Cognito endpoint cannot be accessed from the closed network) Since CognitoJwtVerifier hardcodes the jwksUri from Cognito's user pool (cannot be overridden), I now use the lower-layer JwtRsaVerifier to standardize processing between closed network mode and normal mode.
N/A
> Fix for verifyToken failure bug in closed network mode

- packages/cdk/lib/closed-network-stack.ts
- packages/cdk/lib/construct/closedNetwork/closed-web.ts
- packages/cdk/lib/create-stacks.ts
- packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
Network mode need to be custom('sagemaker') is you build the image on sagemaker code editor.
I confirmed that it was successfully built with this option.
N/A
> Modified to enable deployment of private network options with SageMaker Code Editor

- deploy.sh
> Set Node.js memory limit to 1.5GB (1536MB)

- packages/cdk/lib/construct/closedNetwork/resolver.ts
- props.vpc.selectSubnets()で、SubnetFilter.byIds(props.subnetIds)を使ってサブネットをフィルタしている
- しかし、props.vpcはec2.Vpc.fromLookup()で取得された既存VPCの参照
- CDKのfromLookup()では、指定されたサブネットIDの詳細情報（AZ情報など）が正しく解決されない場合がある
- 結果としてsubnets配列が空になり、58行目のif (ipAddresses.length < 2)でエラーが発生
https://github.com/aws-samples/generative-ai-use-cases/issues/1295
> Fix closed network subnet selection
