packages/cdk/lambda/listChats.ts
packages/cdk/lambda/listMessages.ts
packages/cdk/lambda/repository.ts
packages/cdk/lib/construct/api.ts
packages/types/src/protocol.d.ts
packages/web/src/hooks/useChat.ts
packages/web/src/hooks/useHttp.ts
packages/web/src/hooks/usePredictor.ts
packages/web/src/pages/NotFound.tsx

- チャット一覧の取得
- チャットごとのメッセージ一覧の取得
現状ページネーション入ってません

参照系のAPIの追加

---

README.md
package-lock.json
packages/cdk/lambda/predictStream.ts
packages/cdk/lib/construct/api.ts
packages/cdk/lib/construct/auth.ts
packages/cdk/lib/construct/web.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts
packages/cdk/package.json
packages/types/src/protocol.d.ts
packages/web/package.json
packages/web/src/App.tsx
packages/web/src/components/ChatMessage.tsx
packages/web/src/hooks/useChat.ts
packages/web/src/hooks/usePredictor.ts
packages/web/src/pages/ChatPage.tsx
packages/web/src/pages/PromptTamplatePageBase.tsx
packages/web/src/vite-env.d.ts

レスポンスストリーミング対応

---

packages/web/src/components/ChatMessage.tsx

add inline loading

---

packages/cdk/lib/construct/api.ts

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/31

API エラー時の CORS エラー対応

---

package-lock.json
package.json
packages/cdk/.eslintrc.cjs
packages/cdk/lambda/predict.ts
packages/cdk/lambda/predictStream.ts
packages/cdk/lambda/predictTitle.ts
packages/cdk/lambda/repository.ts
packages/cdk/package.json
packages/web/package.json

unused import などを防止するために設定しました

cdk eslint

---

packages/cdk/lambda/findChatById.ts
packages/cdk/lib/construct/api.ts
packages/types/src/protocol.d.ts
packages/web/src/hooks/useChat.ts
packages/web/src/hooks/useChatApi.ts

useChat の初期化の修正

---

README.md
packages/cdk/cdk.json
packages/cdk/lib/construct/index.ts
packages/cdk/lib/construct/web.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts
packages/web/src/App.tsx
packages/web/src/components/Drawer.tsx
packages/web/src/main.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/vite-env.d.ts
setup-env.sh

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/85

RAG Opt-in 対応

---

packages/web/src/pages/EditorialPage.tsx
packages/web/src/prompts/index.ts

#91 
- プロンプトの改善
- loading によるロックの追加
- コメントのフィルタリングの改善（出力のエラーハンドリングの強化）

文章校正ユースケースの改善

---

packages/web/src/prompts/index.ts

文章校正ユースケースのプロンプトを修正

---

packages/web/src/components/Drawer.tsx
packages/web/src/pages/TranscribePage.tsx

- dark モードの削除 (他でやっていないので)
- file 選択ボタンの cursor を pointer に修正
- 細かい色とスペースの調整

audio-to-text ページのデザインを微修正

---

packages/web/src/hooks/useChat.ts

AIアシスタント回答のtrim処理を削除

---

.github/cfn/oidc-cfn.yml
.github/workflows/review.yml

BedrockによるCodeReview

---

packages/web/src/App.tsx
packages/web/src/components/Drawer.tsx
packages/web/src/pages/Setting.tsx

Issue なし
<summary>
<changeSet>
このプルリクエストでは、サインアウト機能に関連するコードが修正されています。
App.tsx, Drawer.tsx, Setting.tsxの3つのファイルが変更されていて、
サインアウトメニューが削除され、サインアウトハンドラーが実装されるなど、
サインアウト処理に関するUIとロジックが改善されています。
外部インターフェイスや既存の動作への影響は最小限に抑えられていそうです。
</changeSet>
</summary>

サインアウト周りの修正

---

README.md
package-lock.json
packages/cdk/lambda/getWebText.ts
packages/cdk/lib/construct/api.ts
packages/cdk/lib/construct/rag.ts
packages/cdk/package.json
packages/types/src/protocol.d.ts
packages/web/src/App.tsx
packages/web/src/hooks/useChatApi.ts
packages/web/src/hooks/useHttp.ts
packages/web/src/main.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/WebContent.tsx
packages/web/src/prompts/index.ts

新規ユースケースです。URL から Web のコンテンツを抽出します。
<summary>
- Webコンテンツ抽出機能を追加
- フロントエンド: 抽出機能のUI実装
- バックエンド: 抽出APIの実装
- インフラ: 抽出結果の保存先実装
- 抽出機能を呼び出すためのルーティングとパラメータ設定も追加
</summary>

Web コンテンツ抽出

---

packages/cdk/lib/construct/transcribe.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts
packages/web/src/App.tsx
packages/web/src/components/CardDemo.tsx
packages/web/src/components/PopupInterUseCasesDemo.tsx
packages/web/src/hooks/useMicrophone.ts
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/TranscribePage.tsx
packages/web/vite.config.ts

npm run lint した結果結構な diff ができてしまいました

ユースケース連携画面修正

---

packages/web/src/components/MenuDropdown.tsx

Translate タスクでブラウザの幅を縮めても言語を表示させる

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/types/src/image.d.ts

#235
#249 
- Stable Diffusion XL 1.0 対応
- Titan Image での Style Preset 対応（プロンプトに追加）
- typo の修正：TEXT_IMAGE → IMAGE_VARIATION

画像生成ユーズケースの改善

---

packages/web/src/hooks/useGitHub.ts
packages/web/src/pages/Setting.tsx

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/245

最近マージされた PR 一覧を表示

---

packages/web/src/index.css

コードや Shecll コマンドを生成した結果が長文になった際に、横スクロールが出来ない問題がありました。
横スクロールが出来ずに、コードのすべてを目視で確認ができずに不便な利用となりました。
また、コピーもすることが出来ない不便さもありました。
これに対応するため、横スクロール機能を追加する Pull Request となります。
pre タグに css の変更を加えています。
横幅 (width) が固定されておらず、延々と横方向に code 要素が拡張し続けた結果、横スクロールが出来ないまま画面からはみ出る動作となっていました。
「overflow-x: auto」は既に有効になっており、width を固定するように変更する内容です。
再現するプロンプトの一例を挙げます。
・プロンプト
Amazon ECS で RunTask を実行する AWS CLI を生成してください
・モデル : Claude 2.0  (2.1 は気を利かせて途中で改行してくれ再現せず)

コードを生成する際に、横スクロール機能を有効化する

---

packages/web/src/prompts/index.ts

claude2.1/2/instant でも比較的安定して JSON のみを出力するように修正

fix generate image prompt

---

packages/cdk/lambda/predictTitle.ts
packages/cdk/lambda/utils/sagemakerApi.ts
packages/web/src/components/GenerateImageAssistant.tsx
packages/web/src/components/SketchPad.tsx
packages/web/src/hooks/useTranscribe.ts
packages/web/src/hooks/useTranscribeApi.ts

code の typo 修正

---

packages/web/src/hooks/useRagFile.ts

RAGチャットの引用ファイルダウンロードエラー修正

---

README.md
docs/UPDATE.md

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/223

アップデート手順をドキュメントに

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/bedrockAgentApi.ts
packages/cdk/lambda/utils/bedrockApi.ts
packages/web/src/components/ChatMessage.tsx
packages/web/src/hooks/useRag.ts
packages/web/src/pages/ChatPage.tsx
packages/web/src/pages/EditorialPage.tsx
packages/web/src/pages/GenerateTextPage.tsx
packages/web/src/pages/KendraSearchPage.tsx
packages/web/src/pages/RagPage.tsx
packages/web/src/pages/Setting.tsx
packages/web/src/pages/SharedChatPage.tsx
packages/web/src/pages/SummarizePage.tsx
packages/web/src/pages/TranscribePage.tsx
packages/web/src/pages/TranslatePage.tsx
packages/web/src/pages/WebContent.tsx

軽微なドキュメントの修正

---

README.md

README.md の参照以下に、[ブログ: Generative AI Use Cases JP をカスタマイズする方法 (ユースケースの追加方法について解説)](https://aws.amazon.com/jp/blogs/news/how-to-generative-ai-use-cases-jp/) を追加しました。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/284

ブログ: Generative AI Use Cases JP をカスタマイズする方法 (ユースケースの追加方法について解説) を README.md に追加

---

docs/SAML_WITH_ENTRA_ID.md

SAML 認証機能を利用してローカル開発環境を立ち上げる際に、localhost:5173 の URL を追加すると便利な旨を追加。

SAML 認証機能に関する Document に、ローカル開発実施時の localhost:5173 追加の旨を追記

---

package-lock.json
packages/web/package.json
packages/web/src/@types/navigate.d.ts
packages/web/src/components/PromptList.tsx
packages/web/src/hooks/useInterUseCases.ts
packages/web/src/pages/AgentChatPage.tsx
packages/web/src/pages/ChatPage.tsx
packages/web/src/pages/EditorialPage.tsx
packages/web/src/pages/GenerateImagePage.tsx
packages/web/src/pages/GenerateTextPage.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/RagPage.tsx
packages/web/src/pages/SummarizePage.tsx
packages/web/src/pages/TranslatePage.tsx
packages/web/src/pages/WebContent.tsx

Queryパラメータ対応

---

package-lock.json

npm ci や npm install に失敗する場合は node_modules ディレクトリを削除してからお試しください。
それでも失敗する場合は、Issue の起票をお願いします。

パッケージアップデート

---

docs/DEPLOY_OPTION.md
docs/DEVELOPMENT.md
packages/cdk/cdk.json
packages/cdk/lib/construct/api.ts
packages/cdk/lib/dashboard-stack.ts

画像生成のモデルをデフォルト SDXL1 にする

---

packages/cdk/lambda/predict.ts
packages/cdk/lambda/predictStream.ts
packages/cdk/lambda/utils/bedrockApi.ts
packages/cdk/lambda/utils/models.ts
packages/cdk/lambda/utils/prompter.ts
packages/types/src/protocol.d.ts
packages/types/src/utils.d.ts
packages/web/src/components/GenerateImageAssistant.tsx
packages/web/src/hooks/useChat.ts

#270 
Assistant: の後に `<output>` を入れて JSON 以外を出力させづらくする

画像生成 use case の prompt 生成で JSON を出力させる

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/bedrockApi.ts
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/types/src/text.d.ts

新モデルの対応（claud3, meta, mistral）
"anthropic.claude-3-sonnet-20240229-v1:0",
"meta.llama2-13b-chat-v1",
"meta.llama2-70b-chat-v1",
"mistral.mistral-7b-instruct-v0:2",
"mistral.mixtral-8x7b-instruct-v0:1",

新モデルの追加 (Claude3, Mistral, Llama2)

---

packages/cdk/lib/construct/rag.ts

*Issue #344 , if available:*
* rag.ts の S3DataSource と Kendra index の作成に addDependency

add dependency #344

---

packages/cdk/lambda/repository.ts
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/cdk/lib/construct/file.ts
packages/cdk/lib/construct/index.ts
packages/cdk/lib/construct/recognize-file.ts
packages/cdk/lib/construct/web.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts
packages/types/src/message.d.ts
packages/web/src/components/ChatMessage.tsx
packages/web/src/components/InputChatContent.tsx
packages/web/src/hooks/useChat.ts
packages/web/src/hooks/useFileApi.ts
packages/web/src/hooks/useFiles.ts
packages/web/src/hooks/useModel.ts
packages/web/src/pages/ChatPage.tsx
packages/web/src/vite-env.d.ts
setup-env.sh

- Claude 3 のチャットに画像を添付する機能を追加。

Claude3 の画像チャット機能の追加

---

packages/cdk/lambda/utils/models.ts

Llama2 と Mistral のプロンプトテンプレートを修正。
https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-mistral.html

Llama2 と Mistral のプロンプトテンプレートの修正

---

packages/web/src/components/Markdown.tsx

inlineコードが正しく表示されない不具合の修正

---

packages/web/src/hooks/useModel.ts

#352 
モデルドロップダウンに SageMaker エンドポイントが表示されない状態となっていたため修正。

モデルドロップダウンに SageMaker エンドポイントが表示されない不具合の修正

---

packages/cdk/lambda/utils/models.ts
packages/web/.eslintrc.cjs
packages/web/src/components/ChatMessage.tsx
packages/web/src/components/InputChatContent.tsx
packages/web/src/components/ZoomUpImage.tsx
packages/web/src/hooks/useModel.ts

画像を拡大表示できるようにする

---

packages/cdk/lambda/deleteFile.ts
packages/cdk/lib/construct/file.ts
packages/types/src/protocol.d.ts
packages/web/src/components/ButtonIcon.tsx
packages/web/src/components/ChatMessage.tsx
packages/web/src/components/InputChatContent.tsx
packages/web/src/components/ZoomUpImage.tsx
packages/web/src/hooks/useFileApi.ts
packages/web/src/hooks/useFiles.ts
packages/web/src/pages/ChatPage.tsx

アップロードした画像を削除

---

packages/web/src/components/InputChatContent.tsx
packages/web/src/components/Textarea.tsx
packages/web/src/hooks/useFiles.ts

#377 
- クリップボードの画像のペーストに対応（スクリーンショット、画像ファイルのコピー選択など）

クリップボードの画像のペーストに対応

---

packages/web/src/components/ExpandableMenu.tsx
packages/web/src/hooks/useLocalStorage.ts
packages/web/src/hooks/useLocalStorageBoolean.ts
packages/web/src/pages/ChatPage.tsx

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/375

Menu の開閉を localStorage に保存

---

packages/web/src/components/InputChatContent.tsx
packages/web/src/pages/ChatPage.tsx

- 画像入力に対応していないモデルで画像のドラッグドロップとコピーの無効化、画像送信の無効化。
- 画像入力が対応していないモデルに切り替えた際に画像を非表示。画像入力に対応しているモデルに戻した際は表示。

画像ハンドリングの改善

---

packages/web/src/hooks/useChat.ts

(主に) Claude 3 Haiku の streaming が早すぎるのが原因で、表題したエラーが出る。内部で chunk を buffering してステートの更新を遅延させることで、これに対処する。

以下のエラーの修正 Warning: Maximum update depth exceeded.

---

packages/web/src/components/InputChatContent.tsx

画像アップロード中にEnterを押しても送信されないように修正

---

packages/web/src/hooks/useRag.ts

- これまで同一ソース (かつ同一ページ) の別 chunk は別のデータソースとして扱われていた
- そのため、RAG 出力時に表示される参照ドキュメントに同じものが大量に並ぶという現象があった (特に Claude 3)
- 同じドキュメント (かつ同一ページ) の chunk は '...' で結合し 1 つのデータソースとして扱うように変更

RAG で参照するドキュメントをまとめる

---

packages/web/src/prompts/claude.ts

[WIP]claude3 で翻訳 use case の出力結果で余計な出力を出さないようにする

---

docs/DEVELOPMENT.md

ドキュメントに.envファイルの設定方法を記載

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts

Add Model (Mistral Large)
#431

add mistral large

---

README.md
docs/DEPLOY_ON_AWS.md

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/447

AWS 上で完結するデプロイ手順ドキュメントの追加

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/web/index.html

Claude3 Opusに対応

---

docs/DEVELOPMENT.md

素晴らしいOSSプロダクトをありがとうございます。
普段より利用させていただいております。
私がローカルで開発するにあたって躓いたところをマニュアルに追記させていただきました！
ご確認のうえ、よろしければマージください:man-bowing:

ローカル開発時のAWS CLIプロファイルの切り替え方法を記載

---

packages/types/src/utils.d.ts

commit id "ebb44076023552d391ad746227fdd279c9ac026c" での削除内容をtypeに反映

remove unnecessary parameters from the types

---

packages/cdk/lambda/predict.ts
packages/cdk/lambda/predictStream.ts
packages/cdk/lambda/predictTitle.ts

以下警告の修正です。
Cannot invoke an object which is possibly 'undefined'

fix warnings

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/types/src/text.d.ts

add llama3 on bedrock support

---

README.md

none
README に GenU を利用する際の料金試算例を追加しました。
あくまで 1 つのサンプルなので、実際には利用に応じて変動する点もご説明しつつ、料金面を計算のハードルを下げている形です。

README に GenU を利用する際の料金試算例を追加

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/types/src/text.d.ts

Command R/R+に対応

---

packages/cdk/lib/construct/file.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts

chore: typo: fiel -> file 

---

README.md

add JAWS video

---

packages/cdk/lib/construct/rag.ts

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/446
The accesslog will be hierarchical. Other suggestions include, for example, logs/, logs/access/, etc.

fix: accesslog path

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts

add mistral small

---

packages/cdk/lambda/utils/models.ts
packages/web/src/components/SketchPad.tsx
packages/web/src/components/Textarea.tsx
packages/web/src/hooks/useImage.ts
packages/web/src/pages/GenerateImagePage.tsx

- #248 
- Inpaint / Outpaint の対応

画像生成ユーズケースの Inpaint / Outpaint の対応

---

package-lock.json
packages/web/package.json
packages/web/src/App.tsx
packages/web/src/main.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/summit/GenerateDiagramPage.tsx
packages/web/src/prompts/claude.ts

AWS の構成図を draw.io で描画するユースケースを実装しました。
AWS Summit 2024向けの特別実装です。

AWS Diagram Generator

---

packages/cdk/lambda/summit/ehon/check_scenes_audio.py
packages/cdk/lambda/summit/ehon/check_scenes_image.py
packages/cdk/lambda/summit/ehon/check_scenes_text.py
packages/cdk/lambda/summit/ehon/check_summary.py
packages/cdk/lambda/summit/ehon/create_audio.py
packages/cdk/lambda/summit/ehon/create_image.py
packages/cdk/lambda/summit/ehon/create_scene.py
packages/cdk/lib/construct/summit/ehon.ts
packages/cdk/lib/construct/web.ts
packages/cdk/lib/generative-ai-use-cases-stack.ts
packages/web/src/App.tsx
packages/web/src/hooks/summit/useEhon.ts
packages/web/src/main.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/summit/EhonPage.tsx
setup-env.sh

AWS Summit 2024 特別展示用の修正です。
絵本生成機能を追加しています。

add ehon generate function

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts

add Claude 3.5 support

---

package-lock.json
packages/web/package.json
packages/web/src/components/AuthWithSAML.tsx
packages/web/src/components/AuthWithUserpool.tsx
packages/web/src/components/Drawer.tsx
packages/web/src/hooks/useChatApi.ts
packages/web/src/hooks/useHttp.ts
packages/web/src/hooks/useMicrophone.ts
packages/web/src/main.tsx
packages/web/src/pages/Setting.tsx

#452 
v5 -> v6へのアップデートと、それに伴うコードの変更を実施

Amplify UIのアップデート

---

docs/DEPLOY_OPTION.md

modelRegion で Bootstrap が必要な点を追記

Knowledge Base RAG ドキュメント微修正

---

README.md

README に RAG チャットで精度向上するためのブログ記事のリンクを追加

README に RAG チャットで精度向上するためのブログ記事のリンクを追加

---

README.md
docs/DEPLOY_OPTION.md

OpenSearch Service ドキュメント微修正

---

packages/cdk/lib/rag-knowledge-base-stack.ts
packages/web/src/hooks/useRag.ts
packages/web/src/hooks/useRagKnowledgeBase.ts

https://github.com/aws-samples/generative-ai-use-cases-jp/issues/555
以前 Kendra でコントリビュートいただいたものと同様の対応を KB にも行いました。
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/545

RAGチャット (KB) のリンク修正

---

packages/cdk/lambda/utils/bedrockAgentApi.ts
packages/cdk/lambda/utils/bedrockApi.ts
packages/web/index.html

モデルアクセスが設定されていない場合に、マネコンに誘導するエラーメッセージを追加。

モデルアクセス未設定時のエラーメッセージ追加

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts

add Mistral Large (2407)

---

packages/web/src/App.tsx
packages/web/src/components/Alert.tsx
packages/web/src/components/Drawer.tsx
packages/web/src/pages/FileUploadPage.tsx

ファイルアップロード機能 Deprecated (完全廃止予定 2024/09 末)

---

browser-extension/package-lock.json

browser-extension の package-lock.json の更新

---

README.md

READMEのtypoを修正

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts
packages/types/src/image.d.ts
packages/web/src/pages/GenerateImagePage.tsx

add titan image generator v2

---

docs/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/cdk/lib/construct/api.ts

Reverts aws-samples/generative-ai-use-cases-jp#597

Revert "Remove llama2"

---

browser-extension/src/app/features/chat/ChatMessage.tsx
browser-extension/src/app/features/chat/InputContent.tsx
browser-extension/src/app/features/chat/chatSlice.ts
browser-extension/src/app/features/chat/useChat.ts
packages/web/src/components/Markdown.tsx

Markdown コンポーネントの memo 化により改善しました。PC のスペックにより再現しない可能性があると思うので、参考動画を下部に貼ります。Lint によって変更が多く入っていますが、変更したのは Markdown.tsx の 2 行のみです。
https://github.com/user-attachments/assets/0be13d9e-f721-42f4-a491-392613feb1e6
https://github.com/user-attachments/assets/874ec20a-b757-4489-bccb-bbb9d1256aca

長いチャットで入力が遅くなる問題

---

README.md

add case study

---

packages/web/src/components/ChatMessage.tsx
packages/web/src/components/Markdown.tsx

コードブロックが生成された際に１行が長すぎると見切れてしまう

---

docs/DEPLOY_OPTION.md

- SageMaker カスタムエンドポイントデプロイ方法についてドキュメントの微修正

SageMaker カスタムエンドポイントデプロイ方法についてドキュメントの微修正

---

packages/web/src/hooks/useRagKnowledgeBase.ts

- #635 と同様に堅牢な URL エンコーディング処理を実装。
- 検証: 
- S3: 日本語、半角スペース、半角括弧等が含まれたファイルを S3 にアップロード し S3 データソースにて検証。

Knowledge Base RAG の リンクの修正

---

packages/web/src/components/InputChatContent.tsx
packages/web/src/hooks/useRagKnowledgeBase.ts

flex で配置しているためスクロールバーが textarea の中断に出てしまい、若干不格好になっているのを改善。
*Before*
*After*

InputChatContent の改善

---

packages/web/src/hooks/useFiles.ts

- ファイルアップロード機能にて doc および xls ファイルがアップロードできない問題の修正。
- 検証: マクロ入り xls と doc での検証。

ファイルアップロードの修正（doc & xls）

---

package-lock.json
packages/cdk/lambda/utils/bedrockAgentApi.ts
packages/cdk/package.json

#676 
- Agent チャットにてファイルの扱いが一律 CODE_INTERPRETER だったため、Agent 情報を取得し CODE_INTERPRETER が有効化されていない場合は CHAT でファイルを扱うよう変更。

Agent のドキュメントチャット修正

---

packages/cdk/lib/construct/common-web-acl.ts

fix: WAFのIPv6の設定ミス

---

packages/web/src/App.tsx
packages/web/src/pages/LandingPage.tsx
packages/web/src/pages/TranscribePage.tsx
packages/web/src/prompts/claude.ts

- Claude のシステムプロンプトの翻訳
- デモ用のプロンプトの翻訳

Translate Claude's prompt

---

packages/web/src/hooks/useRag.ts
packages/web/src/pages/LandingPage.tsx
packages/web/src/prompts/claude.ts

- プロンプトの politeness の修正
- RAG (Kendra) の出力の翻訳漏れ (参考文献内の "ページ") の修正
N/A

Fix english prompt

---

packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx
packages/web/src/utils/UseCaseBuilderUtils.ts

placeholder と item を修正

---

.github/workflows/node.js.yml
package-lock.json
package.json
packages/web/package.json
packages/web/src/utils/UseCaseBuilderUtils.ts
packages/web/tests/use-case-builder/items.test.ts
packages/web/tests/use-case-builder/placeholders.test.ts
packages/web/vite.config.ts

placeholder や items 部分は壊れやすく仕様をテストにしておくべき実装なため、単体テストを追加
N/A

utils/useCaseBuilderUtils.ts にテストを追加

---

package-lock.json
packages/cdk/lambda/utils/models.ts
packages/cdk/package.json
packages/types/src/message.d.ts
packages/web/src/components/ChatMessage.tsx
packages/web/src/components/InputChatContent.tsx
packages/web/src/components/ZoomUpVideo.tsx
packages/web/src/hooks/useFiles.ts
packages/web/src/pages/AgentChatPage.tsx
packages/web/src/pages/ChatPage.tsx

#759 
Amazon Nova Pro / Light 等の動画をサポートするモデルにて Video Chat に対応

Video Chat 対応

---

packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx

可変項目 => placeholder
見出し => ラベル
N/A

ヒントの表記揺れの修正

---

packages/web/src/pages/Setting.tsx

キャッシュクリア対応

---

packages/cdk/lambda/utils/bedrockAgentApi.ts

AgentチャットでRAGが実行された際に、データソースの表示に不具合があったものを修正しました。具体的にはトレースとチャットの末尾に表示されたデータソースのリンクにアクセスできないこと、ページ数が表示されない問題を修正しました。
なし

AgentチャットのRAGデータソースの表示修正

---

packages/web/src/UseCaseBuilderRoot.tsx
packages/web/src/components/InputText.tsx
packages/web/src/components/Textarea.tsx
packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx

- 左下の Expandable なメニューの視認性が悪いため、左にメニューを新設。
- 「新規作成」をメインメニューに新設。
- 「作成」「更新」ページには disabled の際にエラー文を表示するように改善。
N/A

[ユースケースビルダー] 編集ページの改善

---

packages/cdk/lambda/useCaseBuilder/useCaseBuilderRepository.ts

最近利用したユースケースは、過去に使ったことがある場合、過去のレコードを削除しつつ、最新のものをトップに保存しなおすという動作をしているため、過去に使ったことがあるかどうか調べる際に scan が入る。この scan は避けられないものなため、動作を安定させるために、保存数に上限を設ける。なお、お気に入りについても「自分がお気に入りしているかどうか」を判定するために自分のお気に入りの取得で scan が入るが、お気に入り数は自動で増えていくような性質のデータではないため、こちらは許容している。
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/799

最近利用したユースケースの保存数に上限を設ける

---

packages/types/src/message.d.ts
packages/web/src/components/ChatMessage.tsx
packages/web/src/hooks/useChat.ts
packages/web/src/pages/RagKnowledgeBasePage.tsx

- ExtraData / UploadedFileType の型をより厳密な型に変更、typo による不具合の修正
#823

ExtraData / UploadedFileType 型の修正

---

packages/cdk/lambda/utils/bedrockAgentApi.ts
packages/cdk/lambda/utils/bedrockApi.ts
packages/cdk/lambda/utils/bedrockKbApi.ts
packages/types/package.json
packages/types/src/protocol.d.ts
packages/web/src/components/ChatMessage.tsx
packages/web/src/hooks/useChat.ts
packages/web/src/pages/AgentChatPage.tsx
packages/web/src/pages/ChatPage.tsx
packages/web/src/pages/RagKnowledgeBasePage.tsx

- エラーハンドリングの改善
- エラーメッセージをフロントエンドにも表示するように変更
- リトライボタンの追加
- 最後に生成された文章を再生成できるリトライボタンの追加
#78 
#203 
#773

エラーハンドリングの改善とリトライボタンの追加

---

README.md
packages/cdk/cdk.json
packages/cdk/lib/stack-input.ts

v3 を機会にデフォルトのモデルをアップデートする
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/815

デフォルトモデルのアップデート

---

.gitignore
mkdocs.yml
requirements.txt

Github page 修正

---

packages/cdk/lib/agent-stack.ts
packages/cdk/lib/create-stacks.ts

- Agent Stack のクラス名のリネーム。既存ユーザーへの影響はない
#841

Agent Stack Class リネーム

---

docs/DEPLOY_OPTION.md
packages/cdk/parameter.ts

- Parameter.ts で定義するパラメータは unknown 型なのでエディタの補完が効かない問題の修正

Parameter.ts の修正

---

packages/cdk/lambda/useCaseBuilder/useCaseBuilderRepository.ts

- SAML で認証しているユーザーがユーズケースビルダーでうまくユーズケースを取得、更新できない不具合の修正

SAML 認証ユーザーがユーズケースビルダーでうまく取得・更新できない不具合の修正

---

packages/web/src/hooks/useModel.ts

findModelByModelId 関数の修正

---

packages/cdk/lambda/utils/bedrockAgentApi.ts

Search Agent のリンクが不適切な問題を解決

---

packages/web/src/App.tsx
packages/web/src/hooks/useModel.ts
packages/web/src/pages/LandingPage.tsx

Flows のリファクタリング

---

docs/DEVELOPMENT.md

環境変数が追加・修正されるたびにこちらのドキュメントの更新が必要なのはナンセンスなので、必要な参照先を示した上で具体的な値に関しては書かない方針とした。
なし

DEVELOPMENT.md の修正

---

README.md

新規ブログリンク追加&本日時点でニーズが高そうな順に記事を独断でソート
N/A

add a new reference

---

docs/UPDATE.md

GenU アップデートを自動化する方法の記載

---

.github/workflows/close-stale-issues.yml
packages/web/src/hooks/useOptimizePrompt.ts

新しいモデルが対応されていなかったので追加しました。
https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-management-optimize.html
N/A

プロンプト最適化ツールのモデル対応

---

docs/assets/stylesheets/custom/custom.css
docs/mkdocs/material/overrides/home.html
mkdocs.yml

GitHub Page スタイルの修正

---

docs/DEPLOY_OPTION.md
packages/web/src/hooks/useModel.ts
packages/web/src/pages/RagKnowledgeBasePage.tsx

KnowledgeBase RAG のモデルは modelRegion のものしか選択できないようにする

---

packages/cdk/lambda/utils/models.ts

imageModelIds に指定がないとエラーになるバグの修正

---

README.md

Amazon Q Developer CLIを利用したカスタマイズのブログ記事のリンク追加

---

docs/DEPLOY_OPTION.md

DEPOLY_OPTION ドキュメントの修正

---

packages/cdk/custom-resources/oss-index.js

>変更内容を詳細に説明して下さい。
>既存ユーザーへの影響がある場合 (互換性・デグレ・破壊的変更など) は必ず説明に含めてください。
- 下記エラー修正のため、Lambda 内での props 解析処理を追加
- `ragKnowledgeBaseBinaryVector` 属性をカスタムリソース Lambda に渡す際、CloudFormation の仕様で string として渡される。そのため、CDK で `false` とした場合にも Lambda 内の三項演算子で `true` の分岐を通り、デプロイエラーとなる。
- `false` / `true` の場合いずれも動作確認済み

fix: Ensure proper parsing of custom resource props

---

packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml
packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx

v4 fix translation

---

packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml
packages/web/src/pages/useCaseBuilder/UseCaseBuilderEditPage.tsx

fix locales

---

packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml

V4 fix lint

---

README.md
README_ja.md

Added GenU contribution guide blog to README.

Add GenU contribution guide blog reference to README

---

README_ja.md
packages/web/public/locales/prompts/ja.yaml
packages/web/src/prompts/useCaseBuilderSamples.tsx

When execute npm run lint, it modify the line at 139 of README_ja.md.
It shouldn't.
https://github.com/aws-samples/generative-ai-use-cases/issues/991

npm run lint shouldn't modify the line at 139 of README_ja.md

---

docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/common/src/application/model.ts
packages/types/src/video.d.ts
packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml
packages/web/src/pages/GenerateVideoPage.tsx

Support for Nova Reel v1.1. Also support for MULTI_SHOT_AUTOMATED.
MULTI_SHOT_MANUAL is difficult to implement in terms of UI representation, so it will not be implemented in the first version. In fact, it appears that it has not been implemented in the management console playground yet.
N/A

Nova Reel v1.1 Support

---

package-lock.json
packages/web/package.json
packages/web/src/i18n/config.ts

Add custom formatting functions to i18n/config.js
https://github.com/aws-samples/generative-ai-use-cases/issues/1005

fix i18n format bug issue

---

README.md
README_ja.md

Add the GitHub repository link to README.md / README_ja.md for one click deployment implementation.
#889

Add References for one click GenU deployment

---

README.md
README_ja.md
docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md
packages/cdk/lib/construct/rag.ts
packages/cdk/parameter.ts
packages/cdk/rag-docs/docs/bedrock-ug.pdf.metadata.json
packages/cdk/rag-docs/docs/nova-ug.pdf.metadata.json
packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
packages/common/src/custom/rag-knowledge-base.ts
packages/web/public/locales/translation/en.yaml

- Added sample data in English for RAG
- Added language filter example for Knowledge Bases
- Updated related documentation
- Updated snapshot

Update sample data for RAG

---

docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/common/src/application/model.ts

support writer palmyra x4/x5
#1029

support new model writer palmyra

---

README.md
README_ja.md

chore: update workshop url

---

packages/web/public/locales/translation/en.yaml

Fix English Titles

---

docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md
packages/cdk/lambda/utils/bedrockAgentApi.ts
packages/cdk/lambda/utils/bedrockClient.ts
packages/cdk/lib/create-stacks.ts

Add support for cross-account Agent Chat. (Bedrock Flow and Prompt Optimization Tool are not supported.)

Add support for cross-account agents

---

packages/cdk/lambda/useCaseBuilder/useCaseBuilderRepository.ts
packages/cdk/lib/construct/use-case-builder.ts
packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap
packages/types/src/protocolUseCaseBuilder.d.ts
packages/web/src/hooks/useCaseBuilder/useUseCaseBuilderApi.ts

This PR addresses the latency issues in the UseCase API through the following modifications:
- Parallelized sequential queries
- Increased Lambda memory size of List/Get APIs

Improve UseCase API Performance

---

package-lock.json
packages/cdk/lib/construct/api.ts
packages/cdk/lib/construct/auth.ts
packages/cdk/lib/construct/transcribe.ts
packages/cdk/package.json
packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap

Removed @aws-cdk/aws-cognito-identitypool-alpha and use aws-cdk-lib/aws-cognito-identitypool instead.
N/A

Remove @aws-cdk/aws-cognito-identitypool-alpha

---

packages/web/src/components/Markdown.tsx

- Fixed code block selection and copying functionality during answer generation
- Memoized code block components for improved performance

Fix code block selection and copy button functionality during answer generation

---

packages/web/src/components/ChatList.tsx

Please explain the changes in detail.
If there is any impact on existing users (compatibility, degradation, breaking changes, etc.), be sure to include it in the explanation.
this PR makes the `deleteChat` function calls asynchronous. (really small fix...)
`N/A`

chore(chat): make deleteChat func calls async

---

README.md
docs/overrides/home_en.html

safely -> well-architected
#1070

fix doc text

---

packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml
packages/web/src/pages/TranslatePage.tsx

add translate thai

---

packages/cdk/lambda/utils/models.ts
packages/common/src/application/model.ts
packages/types/src/model.d.ts
packages/web/src/components/GenerateImageAssistant.tsx
packages/web/src/components/Select.tsx
packages/web/src/components/Writer/AdvancedEditor.tsx
packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
packages/web/src/hooks/useModel.ts
packages/web/src/pages/ChatPage.tsx
packages/web/src/pages/GenerateDiagramPage.tsx
packages/web/src/pages/GenerateImagePage.tsx
packages/web/src/pages/GenerateTextPage.tsx
packages/web/src/pages/GenerateVideoPage.tsx
packages/web/src/pages/OptimizePromptPage.tsx
packages/web/src/pages/RagKnowledgeBasePage.tsx
packages/web/src/pages/RagPage.tsx
packages/web/src/pages/SummarizePage.tsx
packages/web/src/pages/TranslatePage.tsx
packages/web/src/pages/VideoAnalyzerPage.tsx
packages/web/src/pages/VoiceChatPage.tsx
packages/web/src/pages/WebContent.tsx

Models are currently all displayed with model IDs, but model names are more user-friendly.
Also, I assigned a legacy flag, but it is not displayed. I added it thinking it might be used for something when reviewing the model list in the future.
https://github.com/aws-samples/generative-ai-use-cases/issues/1052

Display models by name instead of ID

---

packages/cdk/lib/construct/web.ts
packages/cdk/test/__snapshots__/generative-ai-use-cases.test.ts.snap

Addressed by adding blob: to CSP.
N/A

Fixed issue with text-to-speech (Polly) failing in translation feature

---

packages/web/public/locales/prompts/vi.yaml
packages/web/public/locales/translation/vi.yaml
packages/web/src/i18n/config.ts

I have added Vietnamese language support by adding the following files:
packages/web/public/locales/translation/vi.yaml
packages/web/public/locales/prompts/vi.yaml
Modified the following file:
packages\web\src\i18n\config.ts
Fix YAML formatting for Vietnamese language files and add missing translations by this pull request
https://github.com/aws-samples/generative-ai-use-cases/pull/1130

Add Vietnamese localization

---

packages/common/src/application/model.ts

chore: Add cache for Nova Premier

---

packages/web/public/locales/translation/en.yaml
packages/web/public/locales/translation/ja.yaml
packages/web/src/pages/TranslatePage.tsx

Add translate Use Case Vietnamese

---

packages/web/src/pages/MeetingMinutesPage.tsx

議事録生成機能でファイルアップロードが機能していなかった点の修正です。
ファイルアップロード時のテキストが、textarea に渡って居なかったので、それを反映させるように修正しました。
コードが複雑かつ、変数名が直感的ではなかったため、それも修正して見通ししやすいリファクタリングも加えています。
in English
This is a fix for the issue where file upload was not functioning in the meeting minutes generation feature.
The text during file upload was not being passed to the textarea, so I modified it to reflect that.
Since the code was complex and variable names were not intuitive, I also refactored it to make it easier to understand and more readable.
#1178

Fix : 議事録生成機能でファイルアップロードが機能していなかった点の修正

---

README.md
README_ja.md

README に便利にご活用いただける Blog 記事のリンクを追加
none

README に便利にご活用いただける Blog 記事のリンクを追加

---

packages/cdk/lambda/utils/bedrockAgentApi.ts

In Agents Chat, the specification previously ignored conversation history and attached files, but this has been changed to reference them.
N/A

Modified Agents Chat use case to reference conversation history

---

docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md

agentcore doc 追記

---

docs/en/DEPLOY_OPTION.md
docs/ja/DEPLOY_OPTION.md
packages/cdk/lambda/utils/models.ts
packages/common/src/application/model.ts
packages/web/src/pages/GenerateImagePage.tsx

remove eol models
